### PR TITLE
Fix LocalDate persisting dates as the day before

### LINKED ISSUE #2096: Micronaut Data JDBC persisting dates as the day before when connected to a Postgresql database
### Task List

- [x ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ x] Example that reproduces the problem uploaded to Github
- [ x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a class with @MappedEntity annotation that has a LocalDate field and persist the entity with Micronaut Data JDBC connected to a Postgresql database
2. Check the date that's persisted, and you will find that the date is one day before as the one provided to the entity

### Expected Behaviour

The date that's persisted in the database should be the same that was provided.

### Actual Behaviour

The date that's persisted in the database is always one day before what was provided. Oddly enough, when doing extracting queries using the correct date, Micronaut Data is able to find and retrieve the entity correctly. This problem does not happen with a LocalDateTime field.

What happens is the following, in order:

- An entity with a LocalDate field is persisted
- If you query the persisted information using a database manager, you will see that the date is persisted as one day before (I.e: if you persist a date like 2023/12/15 it will be shown in the database as 2023/12/14)
- If you query the persisted information by the date, following the previous example of retrieving the information by providing 2023/12/15 as the date, Micronaut Data finds it and maps the information correctly to the LocalDate field of the class with the correct value of 2023/12/15.

Note: this is not a timezone issue, as both the database and the OS have the correct timezone, and dates persisted directly on the database using regular INSERTs are registered correctly.

### Environment Information

- **Operating System**: Linux Debian Bullseye
- **Micronaut Version:** 3.8.7
- **JDK Version:** 11.0.18
- **Micronaut Data JDBC Version:** 3.9.6
- **Postgresql Database version:** 13.9
- **Postgresql JDBC driver version:** 42.6.0

### Example Application

[localdateissue.zip](https://github.com/micronaut-projects/micronaut-data/files/11183602/localdateissue.zip)

Edit: added Postgresql database version
Second edit: added updated version of the project that also persists a localdatetime for comparison purposes.

### PR DESCRIPTION
**Pull request by radovanradic**
Should fix [issue](https://github.com/micronaut-projects/micronaut-data/issues/2096) that was also [discussed here](https://github.com/micronaut-projects/micronaut-data/discussions/3241)

### CODE REVIEW

File: data-runtime/src/main/java/io/micronaut/data/runtime/convert/DataConversionServiceFactory.java [hunk 1]
```diff
@@ -634,6 +634,9 @@ DataConversionServiceImpl build(@NonNull BeanContext beanContext) {
         // ZonedDateTime
         addZonedConvertorsConvertors(conversionService, ZonedDateTime.class, Function.identity());
 
+        // LocalDate
+        conversionService.addConverter(LocalDate.class, java.sql.Date.class, java.sql.Date::valueOf);
```
Comment (radovanradic) [inline data-runtime/src/main/java/io/micronaut/data/runtime/convert/DataConversionServiceFactory.java:638]: Need to convert to `java.sql.Date` or else converter from core that converts to `UTC` will be used. And we need sql date anyway.

File: data-runtime/src/main/java/io/micronaut/data/runtime/mapper/QueryStatement.java [hunk 2]
```diff
@@ -100,7 +100,7 @@ default QueryStatement<PS, IDX> setDynamic(
                 if (value instanceof Date date) {
                     return setDate(statement, index, date);
                 } else {
-                    return setDate(statement, index, convertRequired(value, Date.class));
+                    return setDate(statement, index, convertRequired(value, java.sql.Date.class));
```
Comment (radovanradic) [inline data-runtime/src/main/java/io/micronaut/data/runtime/mapper/QueryStatement.java:103]: Need to convert to java.sql.Date or else converter from core that converts to UTC will be used. And we need sql date anyway.

**Review by dstepanov — APPROVED** [review]
