### PR TITLE
Fix entity mapping for multiple ONE_TO_MANY relations of the same entity

### LINKED ISSUE #2996: Wrong entity mapping for multiple ONE_TO_MANY relations of the same entity
### Expected Behavior

`ONE_TO_MANY` relations should always be mapped correctly.

### Actual Behaviour

When having multiple `ONE_TO_MANY` relations of the same entity, the entities contains the wrong values.

Having the following data classes and repository:

```kotlin
@MappedEntity
data class Foo(
    @field:Id
    @field:GeneratedValue
    val id: Long? = null,

    @field:Version
    val version: Long? = null,

    @Relation(value = Relation.Kind.MANY_TO_ONE)
    val someBar: Bar? = null,

    @Relation(value = Relation.Kind.MANY_TO_ONE)
    val anotherBar: Bar? = null,
)
```

```kotlin
@MappedEntity
data class Bar(
    @field:Id
    @field:GeneratedValue
    val id: Long? = null,

    @field:Version
    val version: Long? = null,

    @Relation(value = Relation.Kind.ONE_TO_MANY, mappedBy = "someBar")
    val someFoos: List<Foo> = emptyList(),
    @Relation(value = Relation.Kind.ONE_TO_MANY, mappedBy = "anotherBar")
    val otherFoos: List<Foo> = emptyList(),
)
```

```kotlin
@JdbcRepository(dialect = Dialect.POSTGRES)
interface BarRepository : CrudRepository<Bar, Long> {

    @Join(value = "someFoos", type = Join.Type.LEFT_FETCH)
    @Join(value = "otherFoos", type = Join.Type.LEFT_FETCH)
    fun getById(id: Long): Bar
}
```

Only the first element of `someFoos` and `otherFoos` is mapped correctly. The other elements contains wrong values for `someBar` and `anotherBar`.

When multiple `Foo` instances are persisted like this:
```kotlin
repeat(10) {
    fooRepository.save(Foo(someBar = someBar))
}
```

None of the `someFoos` of the fetched  `Bar` entity should have a value for `anotherBar`, but from the second element `someBar` and `anotherBar` are equal.
```kotlin
val fetchedSomeBar = barRepository.getById(someBar.id!!)
fetchedSomeBar.someFoos.forAll { foo ->
        withClue("SomeBar and AnotherBar should be different") {
            foo.someBar?.id shouldNotBe foo.anotherBar?.id
        }
}
```

When adding a `@MappedProperty` in addition to the `@Relation` like this:

```kotlin
@GeneratedValue
@MappedProperty(value = "some_bar_id")
val rawSomeBarId: Long? = null,
```

These `id` values are mapped correctly. The values for `@Relation` are still wrong.

### Steps To Reproduce

1. Clone example application.
2. Run `./gradlew test`.
3. Check report of failed test and test implementation to see details.

### Environment Information

- Operating System: Ubuntu 23.10
- JDK Version: 21.0.1-zulu

### Example Application

https://github.com/davidsonnabend/micronaut-data-relation-mapping-error

### Version

4.5.0

### PR DESCRIPTION
**Pull request by radovanradic**
Fix for #2996

### CODE REVIEW

File: data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java [hunk 1]
```diff
@@ -590,7 +590,8 @@ private <K> K readEntity(RS rs, MappingContext<K> ctx, @Nullable Object parent,
                         entity = setProperty(property, entity, value);
                     } else {
                         final boolean isInverse = parent != null && entityAssociation.getKind().isSingleEnded() && isAssociation && ctx.association.getOwner() == entityAssociation.getAssociatedEntity();
-                        if (isInverse) {
+                        // Before setting property value, check if mappedBy is not different from the property name
+                        if (isInverse && mappedByMatchesOrEmpty(ctx.association, property)) {
                             entity = setProperty(property, entity, parent);
```
Comment (radovanradic) [inline data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java:595]: Without this check, parent entity would be set to all one-to-many collections, disregarding mappedBy attribute on the relation. So, this adds check if mappedBy is set and is matching with the field then can set it.

**Review by dstepanov — APPROVED** [review]
