### PR TITLE
Fix pageable query with join criteria

### LINKED ISSUE #3052: Cannot query pageable with join criteria
### Expected Behavior

Having `Author` and `Book` mapping entities, and relation in `Author`
```
@OneToMany(cascade = CascadeType.ALL, mappedBy = "author")
    private Set<Book> books = new HashSet<>();
```
Defining such query on `Author` repository should work.
```
@Join(value = "books", type = Join.Type.LEFT_FETCH)
    CursoredPage<Author> findByBooksTotalPages(int totalPages, CursoredPageable pageable);
```

### Actual Behaviour

Compile error is thrown telling it is `Unable to implement Repository method:` with the error `Property is not joined at path: books`

This is regression from https://github.com/micronaut-projects/micronaut-data/issues/1882 that was release in micronaut-data 3.9.0 and that code change should be reverted.

### Steps To Reproduce

Explained in expected behavior section.

### Environment Information

Any

### Example Application

_No response_

### Version

micronaut-data since 3.9.0

### PR DESCRIPTION
**Pull request by radovanradic**
Fix for #3052 that was introduced by improper fix for an older issue #1882 which will be reopened.

### CODE REVIEW

File: data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/QueryCriteriaMethodMatch.java [hunk 1]
```diff
@@ -233,14 +233,7 @@ protected MethodMatchInfo build(MethodMatchContext matchContext) {
             for (QueryModel.Criterion criterion : junction.getCriteria()) {
                 countQuery.add(criterion);
             }
-            // Joins are skipped for count query for OneToMany, ManyToMany
-            // however skipping joins from criteria could cause issues (in many to many?)
             for (JoinPath joinPath : queryModel.getJoinPaths()) {
-                Association association = joinPath.getAssociation();
```
Comment (radovanradic) [inline data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/QueryCriteriaMethodMatch.java:239]: The fix for original issue was to remove joins for count query, but that worked only because we had tests with criteria on root entity. Once there are criteria on joined entity, query compilation fails.

So, reverting this will allow query to be compiled and executed, but total size count will not return correct numbers and it's not an easy thing to fix when there are joins. If there is one author with two books, count on author (joined with books) will return 2. And we must add join when there is criteria. The original issue will be reopened.

**Review by graemerocher — APPROVED** [review]

**Comment by graemerocher** [comment]
@dstepanov can this be merged? Would like to do another release

**Review by dstepanov — APPROVED** [review]
