### PR TITLE
Fix to allow reading entities with JSON fields using constructor arguments

### LINKED ISSUE #1058: data-jdbc cannot read an entity with JSON fields when using constructor arguments
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an entity that has a JSON field and has constructor arguments (or a record)
2. Insert a record
3. Read the entity from a repository method.

Example Entity:
```java
@MappedEntity
public record Foo(
    @Id @GeneratedValue @Nullable Integer id, 
    String uid,
    int version,
    @TypeDef(type = DataType.JSON) Map<String, Object> data) {
}
```

### Expected Behaviour
The entity is read and the JSON data is populated.

### Actual Behaviour
Exception with the following error:
`Cannot convert type [class java.lang.String] with value [{foo: bar}] to target type: interface java.util.Map. Consider defining a TypeConverter bean to handle this case.`

### Environment Information

- **Operating System**: Linux and MacOS
- **Micronaut Version:** 2.5.6
- **JDK Version:** 15 and 16

### PR DESCRIPTION
**Pull request by safarmer**
Without this fix, when reading entities with JSON fields through DefaultJdbcRepositoryOperations an exception is thrown reading the JSON field:
`Cannot convert type [class java.lang.String] with value [{foo: bar}] to target type: interface java.util.Map. Consider defining a TypeConverter bean to handle this case.`

This seems partially related to #387

Fixes #1058

### CODE REVIEW

File: data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java [hunk 1]
```diff
@@ -443,6 +443,11 @@ private Object setChildrenAndTriggerPostLoad(Object instance, MappingContext<?>
                                     }
                                 }
                             }
+
+                            if (prop.getDataType() == DataType.JSON && jsonCodec != null) {
```
Comment (dstepanov) [inline data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java:447]: I think this should be something like:
```
if (propertyType.isInstance(v)) {
                    args[i] = v;
                } else {
                    if (dataType == DataType.JSON && jsonCodec != null) {
                       args[i] = jsonCodec.decode(rpp.getArgument(), v.toString());
                    } else {
                        args[i] = resultReader.convertRequired(v, rpp.getArgument());
                    }
                }
```

Comment (safarmer) [reply data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java]: Thanks @dstepanov  I saw that last night when I was looking through broken tests. I will make the change for consistency now. I left it as is incase the JSON value needed to be converted, but this just seems like late night paranoia looking back on it.

I also noticed that the tests I added showed there was also an issue for R2DBC on H2 (no support for decoding JSON?). I have moved my new test 
cases into the existing JSON tests as that seemed to make more sense.

**Comment by safarmer** [comment]
I renamed the PR as after investigating the broken tests and how to properly reproduce. The issue was only present in the code path for entities that have constructor arguments.

File: data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java (hunk 1 above)
Comment (dstepanov) [reply data-runtime/src/main/java/io/micronaut/data/runtime/mapper/sql/SqlResultEntityTypeMapper.java]: I think H2 r2dbc driver doesn't support it yet

**Comment by dstepanov** [comment]
Thanks for the fix @safarmer!

**Comment by alworks** [comment]
@dstepanov Do you know which version is this fix included? Thanks.

**Comment by safarmer** [comment]
@alworks this was released a few days ago in v2.4.5: https://github.com/micronaut-projects/micronaut-data/releases/tag/v2.4.5

**Comment by alworks** [comment]
Thanks!


-Diego Baez

**Comment by alworks** [comment]
I was hoping this was the solution to this pesky problem I have been having, but it did not solve. I tried both v2.4.5 and v2.4.6 and still have the same issue reading from a postres JSONB column, although inserting is fine. My pom.xml includes:

        <dependency>
            <groupId>io.micronaut.data</groupId>
            <artifactId>micronaut-data-jdbc</artifactId>
            <version>2.4.6</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut.sql</groupId>
            <artifactId>micronaut-jdbc-hikari</artifactId>
            <version>3.4.0</version>
            <scope>compile</scope>
        </dependency>

and in annotationProcessorPaths:
                        <path>
                            <groupId>io.micronaut.data</groupId>
                            <artifactId>micronaut-data-processor</artifactId>
                            <version>2.4.6</version>
                        </path>

@MappedEntity class has the column defined as:   
    @NotNull
    @TypeDef(type = DataType.JSON)
    Map<String, String> history;                     

Repositor has the method called defined as:
public abstract class UserRepository implements PageableRepository<User, Long>{
    private final JdbcOperations jdbcOperations;
    
public UserRepository(JdbcOperations jdbcOperations) {
        this.jdbcOperations = jdbcOperations;
    }
    public abstract User findByEmail(String email);
}

and the error I receive is:

[default-nioEventLoopGroup-1-3] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Cannot convert type [class java.lang.String] with value [{"2021-07-04T08:18:02.516984": "Created client-user Mapping(a00d133e-6516-408c-bec2-08fc8ffb423d<->db13@you.com)"}] to target type: interface java.util.Map. Consider defining a TypeConverte
r bean to handle this case.
io.micronaut.data.exceptions.DataAccessException: Cannot convert type [class java.lang.String] with value [{"2021-07-04T08:18:02.516984": "Created client-user Mapping(a00d133e-6516-408c-bec2-08fc8ffb423d
<->db13@you.com)"}] to target type: interface java.util.Map. Consider defining a TypeConverter bean to handle this case.
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.lambda$convertRequired$0(ColumnNameResultSetReader.java:75)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.convertRequired(ColumnNameResultSetReader.java:74)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntity(SqlResultEntityTypeMapper.java:441)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.access$300(SqlResultEntityTypeMapper.java:69)
	at io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper$1.processRow(SqlResultEntityTypeMapper.java:238)
	at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findOne$3(DefaultJdbcRepositoryOperations.java:370)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:155)
