### PR TITLE
Fix query with predication specification and cursored pageable

### LINKED ISSUE #3056: Predicate builder doesn't work with cursored pagination
### Expected Behavior

When I define a repository method signature with a [CursoredPageable](https://micronaut-projects.github.io/micronaut-data/latest/guide/#cursored-pagination) and [PredicateSpecification](https://micronaut-projects.github.io/micronaut-data/latest/guide/#kotlinCriteria) (found only a guide reference for Kotlin) I expect Micronaut Data JDBC to provide a working implementation.

### Actual Behaviour

When I define a repository method signature with a [CursoredPageable](https://micronaut-projects.github.io/micronaut-data/latest/guide/#cursored-pagination) and [PredicateSpecification](https://micronaut-projects.github.io/micronaut-data/latest/guide/#kotlinCriteria) (found only a guide reference for Kotlin) the Micronaut Data JDBC implementation throws _ClassCastException: class io.micronaut.data.model.DefaultPage cannot be cast to class io.micronaut.data.model.CursoredPage_

### Steps To Reproduce

1. Clone the example application
2. Run `mvn test` to get the test _predicateSpecificationWorksWithOffsetPagination_ pass and _predicateSpecificationWorksWithCursoredPagination_ fail

### Environment Information

Java 17

### Example Application

https://github.com/bivapa/micronaut-predicate-builder-with-cursored-pagination-bug-report

### Version

4.5.1

### PR DESCRIPTION
**Pull request by radovanradic**
Fix for #3056

### CODE REVIEW

File: data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/FindPageSpecificationInterceptor.java [hunk 1]
```diff
@@ -53,19 +53,8 @@ public Object intercept(RepositoryMethodKey methodKey, MethodInvocationContext<O
         }
 
         Pageable pageable = getPageable(context);
-        if (pageable.isUnpaged()) {
```
Comment (radovanradic) [inline data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/FindPageSpecificationInterceptor.java:56]: Removing this code because the same is being done below. And the issue was that in the reported issue, `pageable.isUnpaged()` evaluates to true (initialized only with sort, page size is not set) but expected result was `CursoredPage` and here `Page` was immediately returned causing `ClassCastException`.

**Review by graemerocher — APPROVED** [review]

**Review by dstepanov — APPROVED** [review]

**Review by andriy-dmytruk — APPROVED** [review]
