### PR TITLE
Fix hibernate count native query

### LINKED ISSUE #3242: countQuery expecting HQL while using nativeQuery = true
### Expected Behavior

I have repository methods that perform native queries and require pagination. Therefore, I provide a countQuery for this purpose. Here’s a simple example query:

```
@Query(value = "SELECT * FROM ENTERPRISE_GROUP",
            countQuery = "SELECT COUNT(*) FROM ENTERPRISE_GROUP",
            nativeQuery = true)
    Page<EnterpriseGroup> findAllDoesntWork(Pageable pageable);
```

### Actual Behaviour

the countQuery is being evaluated as HQL:
`java.lang.IllegalArgumentException: org.hibernate.query.sqm.UnknownEntityException: Could not resolve root entity 'ENTERPRISE_GROUP'`

However if I use the EnterpriseGroup instead, as I would do in HQL, it works:

```
@Query(value = "SELECT * FROM ENTERPRISE_GROUP",
            countQuery = "SELECT COUNT(*) FROM EnterpriseGroup",
            nativeQuery = true)
    Page<EnterpriseGroup> findAllWorks(Pageable pageable);
```

If I switch back to Micronaut 4.6.3, it behaves the exact opposite way (which I believe is correct): the method with the native countQuery works, while the one with HQL does not;

### Steps To Reproduce

I have provided a simple example application to demonstrate the issue:

1. Run the `QueryTest` class to observe the error.
2. Downgrade to Micronaut 4.6.3 in the `pom.xml` file, and rerun the tests. You will see that the native `countQuery` works, but the HQL `countQuery` stops working.

### Environment Information

- Ubuntu 24.04
- JDK 21
- Micronaut 4.7.0
- 

### Example Application

https://github.com/fdittz/nativequery

### Version

4.7.0

### PR DESCRIPTION
**Pull request by radovanradic**
Fix for #3242

### CODE REVIEW

File: data-processor/src/main/java/io/micronaut/data/processor/visitors/RepositoryTypeElementVisitor.java [hunk 1]
```diff
@@ -449,6 +449,8 @@ private void processMethodInfo(MethodMatchContext methodMatchContext, MethodMatc
                 }
 
                 builder.member(AnnotationMetadata.VALUE_MEMBER, query);
```
Comment (radovanradic) [inline data-processor/src/main/java/io/micronaut/data/processor/visitors/RepositoryTypeElementVisitor.java:451]: Need to populate `nativeQuery` annotation value later being checked in `DefaultStoredQuery`.

**Review by dstepanov — APPROVED** [review]
