### PR TITLE
Fix update by field when entity parameter is present

### LINKED ISSUE #3139: UpdateBy* doesn't work anymore in micronaut-data:4.8
### Expected Behavior

When updating an entity using **`updateBy*`**, the entity is updated using the parameters as criteria

### Actual Behaviour

The entity is not updated anymore

### Steps To Reproduce

1. Clone repository https://github.com/FrogDevelopper/micronaut-4_5
2. Check in [gradle.properties](https://github.com/FrogDevelopper/micronaut-4_5/blob/master/gradle.properties) that micronaut version is **4.4.3** (= micronaut-data:4.7.1)
3. Run test `MyItemRepositoryTest#should_updateByField1` => test pass :white_check_mark:
4. Update [gradle.properties](https://github.com/FrogDevelopper/micronaut-4_5/blob/master/gradle.properties) to use micronaut version **4.5.1** (= micronaut-data:4.8.1)
5. Run again test `MyItemRepositoryTest#should_updateByField1` => test fails :x:

### Environment Information

JDK Version: 21

### Example Application

https://github.com/FrogDevelopper/micronaut-4_5

### Version

4.5.1

### PR DESCRIPTION
**Pull request by radovanradic**
Fix for issue https://github.com/micronaut-projects/micronaut-data/issues/3139

### CODE REVIEW

File: data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/UpdateCriteriaMethodMatch.java [hunk 1]
```diff
@@ -170,12 +170,12 @@ protected <T> Predicate interceptPredicate(MethodMatchContext matchContext,
         final SourcePersistentEntity rootEntity = (SourcePersistentEntity) root.getPersistentEntity();
         Predicate predicate = null;
         if (entityParameter != null) {
-            if (rootEntity.getVersion() != null) {
+            if (rootEntity.getVersion() != null && existingPredicate == null) {
```
Comment (radovanradic) [inline data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/UpdateCriteriaMethodMatch.java:173]: It appears this is used for `void update(Entity entity)` too but also for `void updateByField(String field, Entity entity)` so when there is existing predicate with entity parameter we shouldn't add id and version criteria.
