### PR TITLE
Fix map of objects handling in MongoDb

### LINKED ISSUE #1922: Deserializing Maps with MongoDB
### Expected Behavior

Deserializing an object with a map field should deserialize entries with the correct type.

Given the following entity
```kotlin
@Serdeable
@MappedEntity
data class Parent(
    val firstName: String,
    val lastName: String,
    val children: Map<String, Child>,

    @field: Id
    val id: String = UUID.randomUUID().toString()
)

@Serdeable
data class Child(val location: String)
```

The following test should pass
```kotlin
val id = repository.save(Parent("a", "b", mapOf("child" to Child("nowhere")))).id
val record = repository.findById(id).get()
assertEquals(Child::class, record.children["child"]!!::class)
```

### Actual Behaviour

The map value is deserialized as `Document`. And the test fails with
```
expected: <class com.test.Child> but was: <class org.bson.Document>
```

### Steps To Reproduce

Run tests here https://github.com/cosmin-marginean/micronaut-data-mongo-maps

### Environment Information

JDK17

### Example Application

https://github.com/cosmin-marginean/micronaut-data-mongo-maps

### Version

3.7.4

### PR DESCRIPTION
**Pull request by radovanradic**
Fixes #1922

### CODE REVIEW

File: data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java [hunk 1]
```diff
@@ -187,7 +188,7 @@ public <T> Deserializer<? extends T> findDeserializer(Argument<? extends T> type
         if (codec instanceof MappedCodec) {
             return ((MappedCodec<? extends T>) codec).deserializer;
         }
-        if (codec != null && !(codec instanceof IterableCodec)) {
+        if (codec != null && !(codec instanceof IterableCodec) && !(codec instanceof MapCodec)) {
```
Comment (radovanradic) [inline data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java:191]: I have done a lot of debugging and this is the only fix I found. It might make sense, since there is also special case for `IterableCodec` as `MapCodec` deserialization deserializes object in the map as document and creates `BsonDocument` instead of actual class. This fix lets Micronaut Serde special (de)serializers do the work and fix the issue.

**Review by dstepanov — APPROVED** [review]
