### PR TITLE
Fix resolving mongodb (aggregate) query when it has leading whitespaces

### LINKED ISSUE #3508: CurrentBSONType Error when trying to run@MongoAggregateQuery query
### Expected Behavior

Based on the following, can anyone tell me what I'm doing wrong?

```   
 @MongoAggregateQuery("""
    [
        {
            \$match: {
                eventId: :eventId
            }
        },
        {
            \$unwind: "\$nights"
        },
        {
            \$group: {
                _id: "\$eventId",
                minDate: { \$min: "\$nights.date" },
                maxDate: { \$max: "\$nights.date" }
            }
        },
        {
            \$project: {
                _id: 0,
                minDate: 1,
                maxDate: 1
            }
        }
    ]
    """)
    Optional<EventDateRangeData> findMinMaxDatesByEventId(String eventId)
```

```
@CompileStatic
@Serdeable
@Introspected
class EventDateRangeData {
    LocalDate minDate
    LocalDate maxDate
}
```

I get this error no matter what I change the return value to(Optional, List or just EventDateRangeData):
readStartDocument can only be called when CurrentBSONType is DOCUMENT, not when CurrentBSONType is ARRAY.
The query runs fine in a mongo console. 

I repurposed my sample app here on a different branch to reproduce it:
https://github.com/tucker-eventpipe/sampleApp/tree/bson-type-error

### Actual Behaviour

_No response_

### Steps To Reproduce

_No response_

### Environment Information

_No response_

### Example Application

_No response_

### Version

4.7.6,4.9.2

### PR DESCRIPTION
**Pull request by radovanradic**
Fix for #3508

### CODE REVIEW

File: data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/DefaultMongoStoredQuery.java [hunk 1]
```diff
@@ -133,7 +133,7 @@ final class DefaultMongoStoredQuery<E, R> extends DefaultBindableParametersStore
         this.persistentEntity = persistentEntity;
         OperationType operationType = storedQuery.getOperationType();
         if (operationType == OperationType.QUERY || operationType == OperationType.EXISTS || operationType == OperationType.COUNT) {
-            String query = storedQuery.getQuery();
+            String query = StringUtils.trimLeadingWhitespace(storedQuery.getQuery());
```
Comment (radovanradic) [inline data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/DefaultMongoStoredQuery.java]: The issue was with this 
```
if (query.startsWith("[")) {
                aggregateData = new AggregateData(parseAggregation(query, storedQuery.isCount()));
                findData = null;
```
and when there is `\n` or some other white spaces it won't be recognized and parsing will fail.

File: data-mongodb/src/test/java/io/micronaut/data/document/mongodb/repositories/ElementRowRepository.java [hunk 2]
```diff
@@ -21,10 +21,12 @@ public interface ElementRowRepository extends CrudRepository<ElementRow, ObjectI
     ElementCountResponse customAggregateCount(long eventId, String rowState);
 
     @MongoAggregateQuery("""
+
```
Comment (radovanradic) [inline data-mongodb/src/test/java/io/micronaut/data/document/mongodb/repositories/ElementRowRepository.java:24]: Added `\n` to reproduce issue and validate fix.

File: data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/DefaultMongoStoredQuery.java (hunk 1 above)
Comment (dstepanov) [reply data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/DefaultMongoStoredQuery.java]: Why not `String#trim`?

Comment (radovanradic) [reply data-mongodb/src/main/java/io/micronaut/data/mongodb/operations/DefaultMongoStoredQuery.java]: I was not sure if query can be null and need to add null check first, also was not sure it would remove `\n` but it does so I changed it to trim() in https://github.com/micronaut-projects/micronaut-data/pull/3509/commits/f68630675019406d09672f918e2cb6d4ca4cd41b.

**Comment by radovanradic** [comment]
The build is failing because of netty CVE, will need to get micronaut-core patch to fix it.

**Review by dstepanov — APPROVED** [review]

**Comment by radovanradic** [comment]
> The build is failing because of netty CVE, will need to get micronaut-core patch to fix it.

Update core to 4.9.10 . Now spring 6.2.9 has vulnerability and will need micronaut-spring with spring update to 6.2.10 probably.
EDIT: micronaut-spring 5.11.1 resolves it
