### PR TITLE
Fix pageable queries with dynamic entity name

### LINKED ISSUE #3233: Expandable query parts size should be the same as parameters size + 1
### Expected Behavior

Everything works as with micronaut-data 4.9.x

### Actual Behaviour

I have this repository setup :
```
import io.micronaut.data.jdbc.annotation.JdbcRepository
import io.micronaut.data.model.Pageable
import io.micronaut.data.model.Slice
import io.micronaut.data.model.query.builder.sql.Dialect
import io.micronaut.data.repository.CrudRepository

@JdbcRepository(dialect = Dialect.MYSQL)
interface OutboxJdbcOperations : CrudRepository<OutboxEntryEntity, OutboxEntryId> {
    fun findAll(pageable: Pageable): Slice<OutboxEntryEntity>
}
```
```
@MappedEntity("\${application.datasource.table-prefix}rabbitmq_outbox")
data class OutboxEntryEntity(
    @field:Id
    @MappedProperty("id", type = DataType.LONG)
    val id: OutboxEntryId? = null,
    @MappedProperty("exchange", type = DataType.STRING)
    val exchange: String,
    @MappedProperty("topic", type = DataType.STRING)
    val topic: String,
    @MappedProperty("headers", type = DataType.JSON)
    val headers: Map<String, Any?>,
    @MappedProperty("body", type = DataType.STRING)
    val body: String,
)
```
```
data class OutboxEntryId(
    val value: Long,
) {
    override fun toString(): String {
        return "OutboxEntryId($value)"
    }
}
```

Calling the `findAll` method with a `Pageable` (e.g.: `operations.findAll(Pageable.from(0, count))`) throws the following :
```
java.lang.IllegalStateException: Expandable query parts size should be the same as parameters size + 1. 6 != 1 + 1 SELECT outbox_entry_entity_.`id`,outbox_entry_entity_.`exchange`,outbox_entry_entity_.`topic`,outbox_entry_entity_.`headers`,outbox_entry_entity_.`body` FROM `tester_rabbitmq_outbox` outbox_entry_entity_ [SELECT outbox_entry_entity_.`id`, outbox_entry_entity_.`exchange`, outbox_entry_entity_.`topic`, outbox_entry_entity_.`headers`, outbox_entry_entity_.`body` FROM `tester_rabbitmq_outbox` outbox_entry_entity_, ]
	at io.micronaut.data.runtime.operations.internal.sql.DefaultSqlStoredQuery.<init>(DefaultSqlStoredQuery.java:68)
	at io.micronaut.data.runtime.operations.internal.sql.AbstractSqlRepositoryOperations.decorate(AbstractSqlRepositoryOperations.java:189)
	at io.micronaut.data.runtime.intercept.AbstractQueryInterceptor.findStoreQuery(AbstractQueryInterceptor.java:245)
	at io.micronaut.data.runtime.intercept.AbstractQueryInterceptor.prepareQuery(AbstractQueryInterceptor.java:230)
	at io.micronaut.data.runtime.intercept.DefaultFindSliceInterceptor.intercept(DefaultFindSliceInterceptor.java:55)
	at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:83)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:143)
```

### Steps To Reproduce

_No response_

### Environment Information

_No response_

### Example Application

_No response_

### Version

micronaut 4.7.0, micronaut-data 4.10.x

### PR DESCRIPTION
**Pull request by radovanradic**
This is potential fix for [issue](https://github.com/micronaut-projects/micronaut-data/issues/3233) when entity name has configurable value and uses `Pageable` in find.

### CODE REVIEW

File: data-runtime/src/main/java/io/micronaut/data/runtime/query/internal/DefaultStoredQuery.java [hunk 1]
```diff
@@ -480,4 +493,29 @@ public boolean equals(Object o) {
...
+    private String[] getQueryParts(@NonNull AnnotationValue annotationValue, @NonNull String member) {
+        if (stringsEnvResolverValueMapper != null) {
+            return annotationValue.stringValues(member, stringsEnvResolverValueMapper);
+        }
+        return annotationValue.stringValues(member);
+    }
+
+    private static Function<Object, Object> createEnvResolverValueMapper(Environment environment) {
+        return o -> {
+            PropertyPlaceholderResolver resolver = environment.getPlaceholderResolver();
```
Comment (radovanradic) [inline data-runtime/src/main/java/io/micronaut/data/runtime/query/internal/DefaultStoredQuery.java:506]: This is needed to replace default behavior from `EnvironmentAnnotationValue` which when finds property to resolve also expands strings when finds comma and this is causing this issue creating more query parts than actual parameters.

File: doc-examples/jdbc-example-java/src/main/java/example/CustomEntityRepository.java [hunk 2]
```diff
@@ -1,9 +1,17 @@
...
 import io.micronaut.data.model.query.builder.sql.Dialect;
 import io.micronaut.data.repository.CrudRepository;
 
+import java.util.List;
+
 @JdbcRepository(dialect = Dialect.H2)
 public interface CustomEntityRepository extends CrudRepository<CustomEntity, Long> {
+    Slice<CustomEntity> findAll(Pageable pageable);
+
+    Page<CustomEntity> findByNameIn(List<String> names, Pageable pageable);
```
Comment (dstepanov) [inline doc-examples/jdbc-example-java/src/main/java/example/CustomEntityRepository.java:18]: Can you please add an example of a custom query with IN that does have an expression

Comment (radovanradic) [reply doc-examples/jdbc-example-java/src/main/java/example/CustomEntityRepository.java:18]: Added https://github.com/micronaut-projects/micronaut-data/pull/3245/commits/03324f5cd93aa14de47c310ecc4910912a46e558

Comment (radovanradic) [reply doc-examples/jdbc-example-java/src/main/java/example/CustomEntityRepository.java:18]: It might fix this issue as well https://github.com/micronaut-projects/micronaut-data/issues/2959

**Review by dstepanov — APPROVED** [review]
