### PR TITLE
Fix async over reactive specifications

### LINKED ISSUE #3641: `Subquery::correlate` throwing `IllegalStateException("Not supported operation!")`
### Expected Behavior

On a project built with Micronaut Data Hibernate Reactive and Kotlin Coroutine, building a repository class implementing the `CoroutineJpaSpecificationExecutor` interface, with a method that uses QuerySpecification to dynamically build a query that needs the `Subquery::correlate` method, an IllegalStateException("Not supported operation!") is thrown.

Upon investigation, I discovered it is because the `query: CriteriaQuery<T>` param is defaulting to the `RuntimePersistentEntityCriteriaQuery` implementation—which does NOT provide an implementation to the `correlate` method—instead of Hibernate's `SqmSelectStatement`—which does.

As the project is built using Hibernate, it is expected that Hibernate's implementation is the one used.

P.S. a similar issue was previously discovered and fixed for a Micronaut Data Hibernate Jpa Project: https://github.com/micronaut-projects/micronaut-data/issues/2693

### Actual Behaviour

The following code is throwing an IllegalStateException("Not supported operation!" on the `sub.correlate(root)` part.

```
interface MyRepo : CoroutinePageableCrudRepository<MyClass, UUID>, CoroutineJpaSpecificationExecutor<MyClass> {
 
  fun failingFunction() {

      val spec = QuerySpecification<MstqrPass> { root, query, cb ->
            val predicates = mutableListOf<Predicate>()
            val sub = query.subquery(Int::class.java)
            val correlated = sub.correlate(root).  // failing line
           ...
        }

        return findAll(spec, pageable)
   }
}
```

### Steps To Reproduce

_No response_

### Environment Information

- Micronaut Date Hibernate Reactive
- Kotlin with Kotlin Coroutines

### Example Application

_No response_

### Version

4.10.4

### PR DESCRIPTION
**Pull request by dstepanov**
Fixes https://github.com/micronaut-projects/micronaut-data/issues/3641

### CODE REVIEW

File: data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/async/AbstractAsyncSpecificationInterceptor.java [hunk 1]
```diff
@@ -58,20 +57,20 @@ public abstract class AbstractAsyncSpecificationInterceptor<T, R> extends Abstra
...
-        } else {
+        AsyncRepositoryOperations asyncRepositoryOperations = findRepositoryOperations(AsyncRepositoryOperations.class);
+        if (asyncRepositoryOperations == null) {
             throw new DataAccessException("Datastore of type [" + operations.getClass() + "] does not support asynchronous operations");
         }
-        if (operations instanceof AsyncCriteriaRepositoryOperations asyncCriteriaRepositoryOperations) {
-            asyncCriteriaOperations = asyncCriteriaRepositoryOperations;
-        } else if (asyncOperations instanceof AsyncCriteriaRepositoryOperations asyncCriteriaRepositoryOperations) {
-            asyncCriteriaOperations = asyncCriteriaRepositoryOperations;
-        } else if (operations instanceof AsyncCriteriaCapableRepository repository) {
```
Comment (radovanradic) [inline data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/async/AbstractAsyncSpecificationInterceptor.java:70]: Looks like `findRepositoryOperations()` does not cover `AsyncCriteriaCapableRepository`.
Previous `AbstractAsyncSpecificationInterceptor` constructor did cover it with:
```
    else if (operations instanceof AsyncCriteriaCapableRepository repository) {
        asyncCriteriaOperations = repository.async();
    }
```

Comment (dstepanov) [reply data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/async/AbstractAsyncSpecificationInterceptor.java:70]: Looks like the tests are passing, do you have a different use-case?

**Review by graemerocher — APPROVED** [review]

File: data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/async/AbstractAsyncSpecificationInterceptor.java (hunk 1 above)
Comment (radovanradic) [reply data-runtime/src/main/java/io/micronaut/data/runtime/intercept/criteria/async/AbstractAsyncSpecificationInterceptor.java:70]: No, just noticed `AsyncCriteriaCapableRepository` was being checked and now it's not anymore. If tests are passing then probably it's not an issue.

**Review by radovanradic — APPROVED** [review]
