### PR TITLE
Fix schema generator and query execution when entities have dynamic/configurable mapping value (for Oracle DB)

### LINKED ISSUE #3389: Schema generator for Oracle DB throws error when mapped entity has dynamic name
### Expected Behavior

When we have entity mapped like this 
```
@MappedEntity(value = "${db.config.book-entity}")
public record Book(
    @Id
    @GeneratedValue
    Long id,
    String title) {
}
```
and application properties
```
datasources.default.db-type=oracle
datasources.default.dialect=ORACLE
micronaut.application.name=mn-dynamic-schema
datasources.default.schema-generate=CREATE_DROP
datasources.default.driver-class-name=oracle.jdbc.OracleDriver

db.config.book-entity=THE_BOOK
```
then application should start and generate table.

### Actual Behaviour

Initialization fails with the exception
```
Message: Could not resolve placeholder ${DB.CONFIG.BOOK-ENTITY}
Path Taken:
new @i.m.c.a.Context i.m.d.j.c.SchemaGenerator(List<DataJdbcConfiguration> configurations, JdbcSchemaHandler schemaHandler, Environment environment)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2350)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3146)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.intializeEagerBean(DefaultBeanContext.java:3035)
	at io.micronaut.context.DefaultBeanContext.initializeEagerBean(DefaultBeanContext.java:2704)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2032)
	... 8 more
Caused by: io.micronaut.context.exceptions.ConfigurationException: Could not resolve placeholder ${DB.CONFIG.BOOK-ENTITY}
	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver$PlaceholderSegment.getValue(DefaultPropertyPlaceholderResolver.java:391)
	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver.resolveRequiredPlaceholdersString(DefaultPropertyPlaceholderResolver.java:124)
	at io.micronaut.context.env.DefaultPropertyPlaceholderResolver.resolveRequiredPlaceholders(DefaultPropertyPlaceholderResolver.java:109)
	at io.micronaut.data.jdbc.config.SchemaGenerator.resolveSql(SchemaGenerator.java:238)
	at io.micronaut.data.jdbc.config.SchemaGenerator.generate(SchemaGenerator.java:185)
	at io.micronaut.data.jdbc.config.SchemaGenerator.createSchema(SchemaGenerator.java:132)
```
Because Micronaut data processor converts mapped entity value to uppercase for Oracle database. 
It should probably not do that if mapped value or part of it is configurable value.

### Steps To Reproduce

Use attached application and run tests

[mn-dynamic-entityname.zip](https://github.com/user-attachments/files/19682456/mn-dynamic-entityname.zip)

### Environment Information

Any env and micronaut-data version.

### Example Application

_No response_

### Version

4.8.0 (and earlier)

### PR DESCRIPTION
**Pull request by radovanradic**
Fix for [issue](https://github.com/micronaut-projects/micronaut-data/issues/3389)

### CODE REVIEW

File: data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder2.java [hunk 1]
```diff
@@ -1388,20 +1388,16 @@ private <T> List<T> merge(List<T> left, List<T> right) {
...
-    protected String quote(String persistedName) {
+    protected String quote(String persistedName, boolean supportsDynamicValues) {
         return switch (dialect) {
             case MYSQL, H2 -> '`' + persistedName + '`';
             case SQL_SERVER -> '[' + persistedName + ']';
-            case ORACLE ->
+            case ORACLE -> {
                 // Oracle requires quoted identifiers to be in upper case
-                '"' + persistedName.toUpperCase(Locale.ENGLISH) + '"';
+                String result = supportsDynamicValues ? SqlQueryBuilderUtils.mapPersistedName(persistedName, s -> s.toUpperCase(Locale.ENGLISH)) : persistedName.toUpperCase(Locale.ENGLISH);
```
Comment (radovanradic) [inline data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder2.java:1398]: The root issue was if we have `@MappedEntity("${entity.prefix}_book")` then previous `quote()` implementation would turn it into `${ENTITY.PREFIX}_BOOK` and then when executing query or generating table the app cannot resolve value since in config there is `entity.prefix=tbl_common_`
So this skips uppercase for entries between `${` and `}`

File: data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/AbstractCascadeOperations.java [hunk 2]
```diff
@@ -102,6 +102,10 @@ protected <T> void cascade(AnnotationMetadata annotationMetadata, Class<?> repos
                     case MANY_TO_MANY:
                         final PersistentAssociationPath inverse = association.getInversePathSide().orElse(null);
                         Iterable<Object> children = (Iterable<Object>) association.getProperty().get(entity);
+                        if (children != null) {
```
Comment (radovanradic) [inline data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/AbstractCascadeOperations.java:105]: Faced this issue converting `jdbc-example-records-java`from `H2` to `ORACLE` and it saves cascade data differently so needed to add this fix too.

File: data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/AbstractCascadeOperations.java [hunk 3]
```diff
@@ -185,7 +189,7 @@ protected <T> T afterCascadedMany(T entity, List<Association> associations, Iter
                     }
                 }
             }
-            if (prevChildren != newChildren) {
+            if (association.getProperty().get(entity) != newChildren) {
```
Comment (radovanradic) [inline data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/AbstractCascadeOperations.java:192]: Another fix for cascade save, without this when entity saved then cascade items are not set property after save.

**Review by dstepanov — APPROVED** [review]
