### PR TITLE
Skip insert/update for @GeneratedValue annotated fields in @Embedded

### LINKED ISSUE #3329: Annotation @GeneratedValue is ignored inside @Embedded
### Expected Behavior

A property marked with `@GeneratedValue` which is included using `@Embedded` should be ignored when saving or updating the entity using a `JdbcRepository` (Dialect: POSTGRES).

### Actual Behaviour

The annotation `@GeneratedValue` is ignored and the property is saved or updated with the provided value.

`@GeneratedValue` works for property `example`:

```kotlin
@MappedEntity
data class Entity(
    @Id
    val id: Long,

    @GeneratedValue
    val example: String? = null,

    @Relation(value = Relation.Kind.EMBEDDED)
    val part: Part = Part()
)
```

But it is ignored for `@Embedded` properties like `text`:

```kotlin
@Embeddable
data class Part(
    @GeneratedValue
    val text: String? = null,
)
```

### Steps To Reproduce

1. Clone example application
2. Run test using `./gradlew test`
3. Test will fail because `text` is being changed during `save` and `update`

### Environment Information

- Operating System: MacOS 15.3.1
- JDK Version: 21.0.5-temurin

### Example Application

https://github.com/ingmar-granzow/micronaut-data-generatedvalue-inside-embedded

### Version

4.7.6

### PR DESCRIPTION
**Pull request by radovanradic**
This should fix [issue](https://github.com/micronaut-projects/micronaut-data/issues/3329)

### CODE REVIEW

File: data-model/src/main/java/io/micronaut/data/model/query/builder/sql/AbstractSqlLikeQueryBuilder2.java [hunk 1]
```diff
@@ -791,6 +791,13 @@ public JsonDataType getJsonDataType() {
                 QueryPropertyPath propertyPath = entry.getKey();
                 if (entry.getValue() instanceof BindingParameter bindingParameter) {
                     PersistentEntityUtils.traversePersistentProperties(propertyPath.getPropertyPath(), traverseEmbedded(), (associations, property) -> {
+
+                        boolean generated = PersistentEntityUtils.isPropertyGenerated(entity,
```
Comment (radovanradic) [inline data-model/src/main/java/io/micronaut/data/model/query/builder/sql/AbstractSqlLikeQueryBuilder2.java:795]: There is code that filters persistent properties before building update query, but one of these are embedded and we need to check each fields inside embedded here.

File: data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder.java [hunk 2]
```diff
@@ -1026,7 +1027,8 @@ public int getParameterIndex() {
 
             for (PersistentProperty prop : persistentProperties) {
                 traversePersistentProperties(prop, (associations, property) -> {
-                    if (prop.isGenerated()) {
+                    boolean generated = PersistentEntityUtils.isPropertyGenerated(entity, prop, property);
```
Comment (dstepanov) [inline data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder.java:1030]: Can we somehow fix the prop.isGenerated to return true?

File: data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder2.java [hunk 3]
```diff
@@ -861,7 +861,8 @@ public JsonDataType getJsonDataType() {
 
             for (PersistentProperty prop : persistentProperties) {
                 PersistentEntityUtils.traversePersistentProperties(Collections.emptyList(), prop, (associations, property) -> {
-                    if (prop.isGenerated()) {
```
Comment (radovanradic) [inline data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder2.java:864]: Looks like this check was not valid 
`if (prop.isGenerated()) {`
because `prop` is property being traversed (either single property or association) and I think we should check `property` that is result of `prop` traversal.

Comment (dstepanov) [reply data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder2.java:864]: Right

File: data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder.java (hunk 2 above)
Comment (radovanradic) [reply data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder.java:1030]: Does not look like. We have for example `Author(id)` which is generated in context of `Author` entity insert/update. But, when doing `Book` insert/update then it is not generated and it needs to be updatable. This is why we need more context to check if field is generated ie. involved in insert/update.

**Review by dstepanov — APPROVED** [review]
