### PR TITLE
Fix for runtime criteria containing multi level joins

### LINKED ISSUE #3304: Multi-level joins using JpaSpecificationExecutor result in an IllegalStateException
### Expected Behavior

A repository implementing `JpaSpecificationExecutor` to support dynamic queries using `PredicateSpecification` should also support multi-level joins, similar to repositories implementing `GenericRepository`.

### Actual Behaviour

As soon as a `@Join` annotation for a multi level join is added, an `IllegalStateException` is thrown when the method is called.

### Steps To Reproduce

Having the following simplified entities:

```Kotlin
@MappedEntity
data class Parent(
    @field:Id
    @field:GeneratedValue
    val id: Long? = null,

    val name: String,

    @Relation(value = Relation.Kind.ONE_TO_MANY, cascade = [Relation.Cascade.PERSIST], mappedBy = "parent")
    val children: List<Child> = emptyList(),
)

@MappedEntity
data class Child (
    @field:Id
    @field:GeneratedValue
    val id: Long? = null,

    val name: String,

    @Relation(value = Relation.Kind.MANY_TO_ONE)
    val parent: Parent? = null,

    @Relation(value = Relation.Kind.MANY_TO_ONE)
    val child: GrandChild? = null,
)

@MappedEntity
data class GrandChild(
    @field:Id
    @field:GeneratedValue
    val id: Long? = null,

    val name: String,
)
```

And the following repository:

```Kotlin
@JdbcRepository(dialect = Dialect.H2)
abstract class ParentRepository : CrudRepository<Parent, Long>, JpaSpecificationExecutor<Parent> {

    @Join(value = "children", type = Join.Type.LEFT_FETCH)
    @Join(value = "children.child", type = Join.Type.LEFT_FETCH)
    abstract override fun findAll(spec: PredicateSpecification<Parent>): List<Parent>
}
```

When calling `findAll` the an `IllegalStateException` with the following message is thrown: `"Expected an association for attribute name: children.child"` as the `AbstractPersistentEntityJoinSupport` tries to find the persisted property of name `children.child` using `getPersistentEntity().getPropertyByName(attributeName);`

You can also clone the linked reproducer and run `./gradlew test` to force the error.

### Environment Information

- Operating System: Ubuntu 24.04
- JDK Version: 21.0.6-graal

### Example Application

https://github.com/davidsonnabend/micronaut-multi-level-join

### Version

4.7.4

### PR DESCRIPTION
**Pull request by radovanradic**
Fix for [issue](https://github.com/micronaut-projects/micronaut-data/issues/3304) with nested path joins used in `JpaSpeficifationExecutor` methods.

### CODE REVIEW

**Review by dstepanov — APPROVED** [review]

File: data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractPersistentEntityJoinSupport.java [hunk 1]
```diff
@@ -84,6 +84,21 @@ private <X, Y> PersistentAssociationPath<X, Y> getJoin(String attributeName, io.
...
+        if (persistentProperty == null && attributeName.contains(".")) {
+            int periodIndex = attributeName.indexOf(".");
+            String owner = attributeName.substring(0, periodIndex);
+            PersistentAssociationPath<E, ?> persistentAssociationPath;
+            if (joins.containsKey(owner)) {
+                persistentAssociationPath = joins.get(owner);
+            } else {
+                persistentAssociationPath = (PersistentAssociationPath<E, ?>) join(owner, type);
+            }
+            String remainingJoinPath = attributeName.substring(periodIndex + 1);
```
Comment (dstepanov) [inline data-model/src/main/java/io/micronaut/data/model/jpa/criteria/impl/AbstractPersistentEntityJoinSupport.java:97]: Why +1?
