### PR TITLE
Consider @Where annotation for count query

### LINKED ISSUE #2162: @Where annotation not considered for count query when returning Page
### Expected Behavior

Annotating a findBy method in a PageableRepository with @Where should add the condition to both the find and the count query.

### Actual Behaviour

The find query has the additional condition but the count query doesn't.

### Steps To Reproduce

I have a table "document" that has a column "domain" and "content_type". My Repository method is:

`@Where("document_.content_type = :type")
Page<Document> findByDomain(String domain, String type, Pageable pageable);`

The generated SQL fails when trying to bind the 2nd parameter (type) because the condition is missing in the generated SQL:

`SELECT COUNT(*) FROM "document" document_ WHERE (document_."domain" = ?)`

Please note: 
This is a simplified example. I realize I could do this without the @Where. In my actual code I am joining another table and have a condition on that table.

### Environment Information

MacOS 13.13.1

### Example Application

_No response_

### Version

3.10.0

### PR DESCRIPTION
**Pull request by radovanradic**
Should fix #2162

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -30,3 +30,4 @@ src/main/docs/resources/css/*.css
 src/main/docs/resources/js/*.js
 src/main/docs/resources/style/*.html
 src/main/docs/resources/img/micronaut-logo-white.svg
+**/.micronaut/test-resources/
```
Comment (radovanradic) [inline .gitignore:33]: Some test-resources files started showing up recently, it's safe to ignore these paths.

File: data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/QueryCriteriaMethodMatch.java [hunk 2]
```diff
@@ -255,7 +255,7 @@ protected MethodMatchInfo build(MethodMatchContext matchContext) {
                 }
                 countQuery.join(joinPath.getPath(), joinType, null);
             }
-            countQueryResult = queryBuilder.buildQuery(countQuery);
+            countQueryResult = queryBuilder.buildQuery(annotationMetadataHierarchy, countQuery);
```
Comment (radovanradic) [inline data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/QueryCriteriaMethodMatch.java:258]: This is the cause of the issue, when building count query method annotation metadata is not passed so we don't have information about `@Where` annotation. 
This was probably not done by mistake, maybe wanted to avoid `@Join` or something else but I tested and count query with this change still does not consider joins so should be safe. Anything else @dstepanov could perhaps be the reason why annotation metadata was not passed?

File: .gitignore (hunk 1 above)
Comment (dstepanov) [reply .gitignore:33]: What files are those?

Comment (melix) [reply .gitignore:33]: It's indeed safe to ignore these: the Gradle plugin behavior has been aligned to that of the Maven plugin which creates `.micronaut` directories. This also has the side effect of allowing to use test resources even if not delegating builds to Gradle.

File: data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/QueryCriteriaMethodMatch.java (hunk 2 above)
Comment (dstepanov) [reply data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/QueryCriteriaMethodMatch.java:258]: Probably a mistake

Comment (radovanradic) [reply data-processor/src/main/java/io/micronaut/data/processor/visitors/finders/criteria/QueryCriteriaMethodMatch.java:258]: It was mainly used from tests, removed it https://github.com/micronaut-projects/micronaut-data/pull/2323/commits/df6d6db6ae543edd554965c5d51e48315a2ceaa5
