### PR TITLE
Fix JPA sort with multiple field selection

### LINKED ISSUE #3342: Query has multiple items in the select list error with JPA Projections and Pageable with Sort
### Expected Behavior

With Micronaut `4.3.3` it works fine, after update to `4.7.6` it stop working:

Repository:

```java

@Repository
interface SessionRepository extends CrudRepository<Session, String> {

      Page<SessionDto> findByNip(String nip, Pageable pageable);
}
```

SessionDto

```java
@Value
@Introspected
public class SessionDto {

    String id;
    OffsetDateTime timestamp;
    OffsetDateTime lastUpdated;
    SessionStatus status;

}
```

Session entity

```java
@Getter
@Setter
@Entity
@DynamicUpdate
public class Session implements Serializable {

    @Id
    private String id;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private OffsetDateTime timestamp;

    @UpdateTimestamp
    private OffsetDateTime lastUpdated;

    @Tolerate
    public Session() {
    }

    @NotEmpty
    private String nip;

    @Enumerated(EnumType.STRING)
    @NotNull
    private SessionStatus status;

    @NotEmpty
    private String token;

    @Builder
    public Session(@NotEmpty String id, @NotEmpty String nip, @NotNull SessionStatus status, @NotEmpty String token) {
        this.id = id;
        this.nip = nip;
        this.status = status;
        this.token = token;
    }
}
```

repository method call:

````java
val page = sessionRepository.findByNip(
                identifier,
                Pageable.from(criteria.getPageOffset(), criteria.getPageSize(), Sort.of(Sort.Order.desc("timestamp"))));
````

exception:

```shell
org.hibernate.query.IllegalQueryOperationException: Query has multiple items in the select list
	at org.hibernate.query.sqm.internal.SqmUtil.sortSpecification(SqmUtil.java:851)
	at org.hibernate.query.sqm.internal.AbstractSqmSelectionQuery.lambda$setOrder$0(AbstractSqmSelectionQuery.java:137)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.hibernate.query.sqm.internal.AbstractSqmSelectionQuery.setOrder(AbstractSqmSelectionQuery.java:138)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.setOrder(QuerySqmImpl.java:775)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.setOrder(HibernateJpaOperations.java:235)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.setOrder(HibernateJpaOperations.java:95)
	at io.micronaut.data.hibernate.operations.AbstractHibernateOperations.bindPageable(AbstractHibernateOperations.java:643)
	at io.micronaut.data.hibernate.operations.AbstractHibernateOperations.bindPreparedQuery(AbstractHibernateOperations.java:533)
	at io.micronaut.data.hibernate.operations.AbstractHibernateOperations.collectResults(AbstractHibernateOperations.java:384)
	at io.micronaut.data.hibernate.operations.AbstractHibernateOperations.collectFindAll(AbstractHibernateOperations.java:363)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$findAll$8(HibernateJpaOperations.java:325)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.lambda$executeRead$21(HibernateJpaOperations.java:566)
	at io.micronaut.transaction.support.AbstractPropagatedStatusTransactionOperations.lambda$execute$2(AbstractPropagatedStatusTransactionOperations.java:68)
	at io.micronaut.transaction.TransactionCallback.apply(TransactionCallback.java:37)
	at io.micronaut.transaction.support.AbstractTransactionOperations.executeTransactional(AbstractTransactionOperations.java:333)
	at io.micronaut.transaction.support.AbstractTransactionOperations.executeWithNewTransaction(AbstractTransactionOperations.java:318)
	at io.micronaut.transaction.support.AbstractTransactionOperations.executeNew(AbstractTransactionOperations.java:235)
	at io.micronaut.transaction.support.AbstractTransactionOperations.doExecute(AbstractTransactionOperations.java:137)
	at io.micronaut.transaction.support.AbstractTransactionOperations.lambda$doExecute$0(AbstractTransactionOperations.java:122)
	at io.micronaut.data.connection.support.AbstractConnectionOperations.executeWithNewConnection(AbstractConnectionOperations.java:167)
	at io.micronaut.data.connection.support.AbstractConnectionOperations.execute(AbstractConnectionOperations.java:114)
	at io.micronaut.transaction.support.AbstractTransactionOperations.doExecute(AbstractTransactionOperations.java:120)
	at io.micronaut.transaction.support.AbstractPropagatedStatusTransactionOperations.execute(AbstractPropagatedStatusTransactionOperations.java:65)
	at io.micronaut.transaction.TransactionOperations.executeRead(TransactionOperations.java:76)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.executeRead(HibernateJpaOperations.java:566)
	at io.micronaut.data.hibernate.operations.HibernateJpaOperations.findAll(HibernateJpaOperations.java:323)
	at io.micronaut.data.runtime.intercept.DefaultAbstractFindPageInterceptor.intercept(DefaultAbstractFindPageInterceptor.java:62)
	at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:83)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:143)
```

when I remove ordering:

```java
val page = sessionRepository.findByNip(
                identifier,
                Pageable.from(criteria.getPageOffset(), criteria.getPageSize()));
```

it works again, but it is no resolution for me....

I'm trying with upgraded Micronaut Data: `<micronaut.data.version>4.11.1</micronaut.data.version>` - the same problem.

### Actual Behaviour

_No response_

### Steps To Reproduce

_No response_

### Environment Information

- Linux Mint
- PostgreSQL 14.11
- JDK 21

### Example Application

_No response_

### Version

4.10.5 and 4.11.1

### PR DESCRIPTION
**Pull request by radovanradic**
Fixes #3342

### CODE REVIEW

File: data-jdbc/src/test/groovy/io/micronaut/data/jdbc/postgres/PostgresColumnTransformerSpec.groovy [hunk 1]
```diff
@@ -88,7 +88,7 @@ class Rider {
 
     String name
 
-    @ColumnTransformer(read = "to_char(@.finish_time, 'PTHH24HMIM')")
+    @ColumnTransformer(read = "to_char(finish_time, 'PTHH24HMIM')")
```
Comment (dstepanov) [inline data-jdbc/src/test/groovy/io/micronaut/data/jdbc/postgres/PostgresColumnTransformerSpec.groovy:91]: Is it needed?

**Review by dstepanov — CHANGES_REQUESTED** [review]

File: data-jdbc/src/test/groovy/io/micronaut/data/jdbc/postgres/PostgresColumnTransformerSpec.groovy (hunk 1 above)
Comment (radovanradic) [reply data-jdbc/src/test/groovy/io/micronaut/data/jdbc/postgres/PostgresColumnTransformerSpec.groovy:91]: In prev PR I thought `@.` is needed for `@ColumnTransformer` but it works without it so just reverting change here.

Comment (dstepanov) [reply data-jdbc/src/test/groovy/io/micronaut/data/jdbc/postgres/PostgresColumnTransformerSpec.groovy:91]: ok

**Review by dstepanov — APPROVED** [review]
