### PR TITLE
Fix warnings and errors with asciidoc generation.

### LINKED ISSUE #1338: Broken docs generation
### Issue description

While working on upgrading to the latest [AsciidoctorJ version for the Micronaut Build plugins](https://github.com/micronaut-projects/micronaut-build/pull/269), I used this project to verify that I wasn't breaking anything.

However, doing so I discovered that docs generation already issues quite a few warnings, and some includes are probably broken: https://ge.micronaut.io/s/3l2ovln6drrzg/console-log#L384

### PR DESCRIPTION
**Pull request by wetted**
fixes #1338

### CODE REVIEW

**Comment by wetted** [comment]
This doesn't resolve all of the asciidoc generations warnings, and they probably won't be, for example:

It seems we get this error for `snippet::` macros. I spot checked several of these. The so-called missing callouts are in the docs-example language source files. 
```
Rendering document file introduction.adoc
<stdin>: line 25: no callout found for <1>
<stdin>: line 26: no callout found for <2>
```

I corrected some of these section title levels, but some didn't look as good, so I left what is more readable, IMO.
```
Rendering document file kotlinCriteria.adoc
<stdin>: line 15: section title out of sequence: expected level 1, got level 2
<stdin>: line 65: section title out of sequence: expected level 1, got level 2
```

Not everything is supported in all three languages, so missing tags is a consequence of that.
```
Rendering document file typeSafeJava.adoc
<stdin>: line 10: tag typesafe not found in include file: /Users/wetted/Development/projects/micronaut/micronaut-data/doc-examples/jdbc-example-groovy/src/main/groovy/example/PersonRepository.groovy
<stdin>: line 16: tag typesafe not found in include file: /Users/wetted/Development/projects/micronaut/micronaut-data/doc-examples/jdbc-example-kotlin/src/main/kotlin/example/PersonRepository.kt
```

Not everything is supported in all three languages, so missing source files is a consequence of that.
```
Rendering document file javaRecords.adoc
!!!! WARNING: NO FILE FOUND MATCHING TARGET PASSED IN AT PATH : /Users/wetted/Development/projects/micronaut/micronaut-data/doc-examples/jdbc-example-records-groovy/src/main/groovy/example/Book.groovy
!!!! WARNING: NO FILE FOUND MATCHING TARGET PASSED IN AT PATH : /Users/wetted/Development/projects/micronaut/micronaut-data/doc-examples/jdbc-example-records-kotlin/src/main/kotlin/example/Book.kt

```

File: doc-examples/jdbc-example-kotlin/src/main/kotlin/example/UserRepositoryWithWhere.kt [hunk 1]
```diff
@@ -0,0 +1,9 @@
+package example
+
+import io.micronaut.data.annotation.Where
+
+interface UserRepositoryWithWhere {
+    // ...
+    @Where("@.enabled = false")
+    fun findDisabled(): List<User?>?
```
Comment (sdelamo) [inline doc-examples/jdbc-example-kotlin/src/main/kotlin/example/UserRepositoryWithWhere.kt:8]: can this be: 
```suggestion
    fun findDisabled(): List<User>
```

**Review by sdelamo — APPROVED** [review]

**Review by melix — APPROVED** [review]

**Review by dstepanov — APPROVED** [review]
