### PR TITLE
Fix issue with CursoredPageable and @EmbeddedId

### LINKED ISSUE #3407: Issue with CursoredPageable and @EmbeddedId
### Expected Behavior

I'm running into an issue trying to use CursoredPageable on a repository whose entity is keyed by a complex primary key modeled as an @EmbeddedId . For example:

```
@Embeddable
public record AssetId(
        @MappedProperty("container_id")
        UUID containerId,
        @MappedProperty("asset_id")
        Integer assetId
) {
}

@MappedEntity("assets")
public record EphemeralAsset(
    @EmbeddedId
    AssetId id
){}

@JdbcRepository(dialect =  Dialect.POSTGRES)
public interface EphemeralAssetsRepository extends PageableRepository<EphemeralAsset, AssetId> {

    CursoredPage<EphemeralAsset> findByIdContainerId(UUID containerId, CursoredPageable pageable);
}

```

When invoking `findByContainerId` the generated query tries to add a sort clause for `assets.id` which is a column that does not exist. I think the EmbeddedId should be expanded to sort clauses for both `assets.container_id` and `assets.asset_id`. Is this a bug in Micronaut Data query generation or a misunderstanding on how EmbeddedId should be working?

### Actual Behaviour

When invoking findByContainerId the generated query tries to add a sort clause for `assets.id` which is a column that does not exist.

### Steps To Reproduce

_No response_

### Environment Information

_No response_

### Example Application

[Example Application](https://github.com/cutz/mn-data-i3407)

### Version

4.8.2

### PR DESCRIPTION
**Pull request by radovanradic**
Fix for #3407

### CODE REVIEW

File: data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/sql/DefaultSqlPreparedQuery.java [hunk 1]
```diff
@@ -222,10 +227,14 @@ public static Sort enhanceCursoredSort(Sort sort, boolean isBackwards, Persisten
...
         List<Order> orders = new ArrayList<>(sort.getOrderBy());
         for (PersistentProperty idProperty: persistentEntity.getIdentityProperties()) {
-            String name = idProperty.getName();
-            if (orders.stream().noneMatch(o -> o.getProperty().equals(name))) {
-                orders.add(Order.asc(name));
-            }
+            PersistentEntityUtils.traversePersistentProperties(idProperty, (associations, property) -> {
+                String prefix = String.join(".", associations.stream().map(Association::getName).collect(Collectors.toList()));
+                String propertyName = property.getName();
+                String name = StringUtils.isEmpty(prefix) ? propertyName : prefix + "." + propertyName;
```
Comment (dstepanov) [inline data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/sql/DefaultSqlPreparedQuery.java:232]: Should we use the naming stratefy here somehow?

Comment (radovanradic) [reply data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/sql/DefaultSqlPreparedQuery.java:232]: We need to build `shipmentId.country` etc. here and not with `_` like strategy has methods for so maybe we can leave it like this for just this case.

**Review by graemerocher — APPROVED** [review]

**Review by dstepanov — APPROVED** [review]
