### PR TITLE
Fix many-to-one (and one-to-one) join

### LINKED ISSUE #3327: Joined object correctly joins using @Where clause, but still tries to create object with only ID present
### Expected Behavior

I create a classes like so:

```kt
@MappedEntity
data class Document(
    @field:Id
    @GeneratedValue
    val id: UUID? = null,
    val name: String,
    @Relation(value = Relation.Kind.MANY_TO_ONE)
    val type: DocumentType? = null
)

@MappedEntity
@Where("@.deleted = false")
data class DocumentType(
    @field:Id
    @GeneratedValue
    val id: Long? = null,
    val name: String,
    val deleted: Boolean = false
)

@Join("type", type = Join.Type.LEFT_FETCH)
@JdbcRepository(dialect = Dialect.POSTGRES)
interface DocumentRepository : CrudRepository<Document, UUID>
```

When doing `documentRepository.findById(...)`, where `document` has `type` that is deleted, I should get back `document` which has `document.type = null`

### Actual Behaviour

I get back error 
```
Null value read for non-null constructor argument [name] of type: [...].DocumentType
```

This is because the generated join correctly adds in the where clause
```sql
LEFT JOIN "document_type" document_type_
          ON document_."type_id" = document_type_."id" AND document_type_.deleted = false
```

BUT the ID field is not selected from the table
```sql
       document_."type_id",
       document_type_."name"                                                     AS type_name,
       document_type_."deleted"                                                  AS type_deleted,
```

I presume the fix is quite easy, to just select the ID from the joining table. I would really appreciate if anybody knows a workaround until then. 

### Steps To Reproduce

_No response_

### Environment Information

Micronaut 4.7.6 and micronaut-data 4.11.1

### Example Application

_No response_

### Version

4.7.6

### PR DESCRIPTION
**Pull request by radovanradic**
This might be the fix for [issue](https://github.com/micronaut-projects/micronaut-data/issues/3327). The idea is not `SELECT` entity id for many-to-one and one-to-one relation and only `SELECT` entity and its fields if joined.
However, it does change previous behavior and does not select entities with just id for many-to-one, one-to-one, which I think is correct way and fixes original issue).

### CODE REVIEW

File: data-processor/src/test/groovy/io/micronaut/data/model/jpa/criteria/CriteriaSpec.groovy [hunk 1]
```diff
@@ -92,7 +92,7 @@ class CriteriaSpec extends AbstractCriteriaSpec {
             String query = getSqlQuery(criteriaQuery)
 
         expect:
-            query == '''SELECT book_."id",book_."author_id",book_."title",book_."total_pages",book_."last_updated" FROM "book" book_ WHERE (book_."id" IN (SELECT book_book_."id" FROM "book" book_book_ WHERE (book_book_."id" = 123)))'''
```
Comment (radovanradic) [inline data-processor/src/test/groovy/io/micronaut/data/model/jpa/criteria/CriteriaSpec.groovy:95]: Does not return field from the association if not requested by join for retrieval

File: data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildUpdateSpec.groovy [hunk 2]
```diff
@@ -524,7 +524,7 @@ interface BookRepository extends GenericRepository<Book, Long> {
         when:
             def updateReturningCustomMethod = repository.findPossibleMethods("updateReturning").findFirst().get()
         then:
-            getQuery(updateReturningCustomMethod) == 'UPDATE "book" SET "author_id"=?,"genre_id"=?,"title"=?,"total_pages"=?,"publisher_id"=?,"last_updated"=? WHERE ("id" = ?) RETURNING "id","author_id","genre_id","title","total_pages","publisher_id","last_updated"'
```
Comment (radovanradic) [inline data-processor/src/test/groovy/io/micronaut/data/processor/sql/BuildUpdateSpec.groovy:527]: Returning also returns only fields belonging to the entity. This might be the most significant change, not sure if returning could have `@Join` annotation to tell Micronaut Data to return joined entities?

File: data-tck/src/main/java/io/micronaut/data/tck/entities/SaleItem.java [hunk 3]
```diff
@@ -30,7 +31,7 @@ public class SaleItem {
     private Long id;
 
     @Relation(value = Relation.Kind.MANY_TO_ONE, cascade = Relation.Cascade.ALL)
-    @MappedProperty("fk_sale_id")
+    @JoinColumn(name = "sale_id", referencedColumnName = "id")
```
Comment (dstepanov) [inline data-tck/src/main/java/io/micronaut/data/tck/entities/SaleItem.java]: Is it needed?

Comment (radovanradic) [reply data-tck/src/main/java/io/micronaut/data/tck/entities/SaleItem.java]: Looks like not needed, I had issues with it but looks like due to local gradle cache. Removed.

**Review by dstepanov — APPROVED** [review]
