### PR TITLE
Fixes #1950 when using @Where with parameters in r2dbc PostgreSQL

### LINKED ISSUE #1950: @Where parameterization does not work with R2dbc Postgres
### Expected Behavior

Parameterized @Where statements like:

```
    @Where(value = "total_pages > :pages")
    public abstract List<Book> findByTitleStartsWith(String title, int pages);
```
should work and add the additional where statement.

### Actual Behaviour

Query compilation works, but fails at Runtime with the following error:

```java
io.micronaut.transaction.exceptions.TransactionSystemException: Error invoking doInTransaction handler: Binding index 1 when only 1 parameters are expected
	at io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations.lambda$withTransaction$15(DefaultR2dbcRepositoryOperations.java:479)
	at reactor.core.publisher.FluxUsingWhen.deriveFluxFromResource(FluxUsingWhen.java:120)
	at reactor.core.publisher.FluxUsingWhen.access$000(FluxUsingWhen.java:54)
	at reactor.core.publisher.FluxUsingWhen$ResourceSubscriber.onNext(FluxUsingWhen.java:193)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2034)
	at reactor.core.publisher.MonoHasElements$HasElementsSubscriber.onComplete(MonoHasElements.java:93)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
	at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onComplete(FluxDiscardOnCancel.java:104)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:222)
	at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onComplete(FluxDiscardOnCancel.java:104)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
	at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:460)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:805)
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.complete(FluxCreate.java:753)
	at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:247)
	at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:213)
	at reactor.core.publisher.FluxCreate$SerializedFluxSink.complete(FluxCreate.java:204)
	at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.complete(ReactorNettyClient.java:671)
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:937)
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:813)
	at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:719)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:128)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:292)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:401)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:411)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IndexOutOfBoundsException: Binding index 1 when only 1 parameters are expected
	at io.r2dbc.postgresql.client.Binding.add(Binding.java:75)
	at io.r2dbc.postgresql.PostgresqlStatement.bind(PostgresqlStatement.java:107)
	at io.r2dbc.postgresql.PostgresqlStatement.bind(PostgresqlStatement.java:58)
	at io.micronaut.data.r2dbc.mapper.R2dbcQueryStatement.setValue(R2dbcQueryStatement.java:144)
	at io.micronaut.data.r2dbc.mapper.R2dbcQueryStatement.setInt(R2dbcQueryStatement.java:222)
	at io.micronaut.data.r2dbc.mapper.R2dbcQueryStatement.setInt(R2dbcQueryStatement.java:39)
	at io.micronaut.data.runtime.mapper.QueryStatement.setDynamic(QueryStatement.java:79)
	at io.micronaut.data.r2dbc.mapper.R2dbcQueryStatement.setDynamic(R2dbcQueryStatement.java:135)
	at io.micronaut.data.r2dbc.mapper.R2dbcQueryStatement.setDynamic(R2dbcQueryStatement.java:39)
	at io.micronaut.data.runtime.operations.internal.sql.AbstractSqlRepositoryOperations.setStatementParameter(AbstractSqlRepositoryOperations.java:238)
	at io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations.access$5600(DefaultR2dbcRepositoryOperations.java:133)
	at io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations$R2dbcParameterBinder.bindOne(DefaultR2dbcRepositoryOperations.java:1141)
	at io.micronaut.data.runtime.operations.internal.query.DefaultBindableParametersStoredQuery.bindParameter(DefaultBindableParametersStoredQuery.java:168)
	at io.micronaut.data.runtime.operations.internal.query.DefaultBindableParametersStoredQuery.bindParameters(DefaultBindableParametersStoredQuery.java:84)
	at io.micronaut.data.runtime.operations.internal.query.DefaultBindableParametersPreparedQuery.bindParameters(DefaultBindableParametersPreparedQuery.java:82)
	at io.micronaut.data.runtime.operations.internal.query.BindableParametersPreparedQuery.bindParameters(BindableParametersPreparedQuery.java:51)
	at io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations$DefaultR2dbcReactiveRepositoryOperations.lambda$findAll$17(DefaultR2dbcRepositoryOperations.java:733)
	at io.micronaut.data.r2dbc.operations.DefaultR2dbcRepositoryOperations.lambda$withTransaction$15(DefaultR2dbcRepositoryOperations.java:474)
	... 51 common frames omitted
```

This appears to be because of [this line in R2dbcRepository](https://github.com/micronaut-projects/micronaut-data/blob/master/data-r2dbc/src/main/java/io/micronaut/data/r2dbc/annotation/R2dbcRepository.java#L49)

when Pattern replacement happens in [AbstractSqlLikeQueryBuilder](https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java#L1034),  the `$` character is a special character for group reference, so the replacement fails (it actually substitutes in an empty string).

### Steps To Reproduce

1. Create a Repository with a @Where with a parameter
2. Invoke that method

### Environment Information

MacOS
JDK 17

### Example Application

_No response_

### Version

3.7.2 (happens on lower versions as well)

### PR DESCRIPTION
**Pull request by edeesis**
fixes #1950

### CODE REVIEW

File: data-model/src/main/java/io/micronaut/data/annotation/Where.java [hunk 1]
```diff
@@ -35,9 +35,10 @@
     /**
      * The string value that represents the additional query criterion. For example: {@code enabled = true}
      *
-     * <p>Note that if it may be required to specify the query alias in queries. For example: {@code book_.enabled = true}</p>
+     * <p>Note that if it may be required to specify the query alias in queries. For example: {@code book_.enabled = true}.
+     * `@` can be used as a placeholder for the query's alias</p>
      *
-     * <p>Parameterized variables can be specified using the dollar syntax: {@code book_.enabled = ${enabled}}. In
+     * <p>Parameterized variables can be specified using the dollar syntax: {@code book_.enabled = :enabled}. In
```
Comment (edeesis) [inline data-model/src/main/java/io/micronaut/data/annotation/Where.java:41]: opportunistic, since this syntax appears to be out of date.

File: data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/postgres/PostgresRepositorySpec.groovy [hunk 2]
```diff
@@ -158,4 +158,16 @@ class PostgresRepositorySpec extends AbstractRepositorySpec implements PostgresT
         return true
     }
 
+    void "test @Where annotation"() {
```
Comment (edeesis) [inline data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/postgres/PostgresRepositorySpec.groovy:161]: this test failed with an exception before the change in AbstractSqlLikeQueryBuilder.java

**Comment by edeesis** [comment]
I don't see a way to retry the build, it looks like it simply died while running the tests.

**Comment by radovanradic** [comment]
> I don't see a way to retry the build, it looks like it simply died while running the tests.

I have restarted builds few times and finally it passed. @dstepanov Should this target 3.9.x or can go to master?

**Comment by edeesis** [comment]
Thanks @radovanradic

File: data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java [hunk 3]
```diff
@@ -1031,7 +1031,8 @@ private void appendAdditionalWhere(StringBuilder queryClause, QueryState querySt
             while (matcher.find()) {
                 String name = matcher.group(3);
                 String placeholder = queryState.addAdditionalRequiredParameter(name);
-                matcher.appendReplacement(additionalWhereBuilder, placeholder);
+                //appendReplacement considers $ to be a special character, need to escape it.
```
Comment (dstepanov) [inline data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java:1034]: It would be better to have `Pattern#quote`

**Review by dstepanov — CHANGES_REQUESTED** [review]

**Comment by dstepanov** [comment]
Sorry, I lost your PR over the holidays. Yes, please target `3.9.X`. Thanks!

File: data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java (hunk 3 above)
Comment (edeesis) [reply data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java:1034]: Pattern.quote
```java
matcher.appendReplacement(additionalWhereBuilder, Pattern.quote(placeholder));
```

 results in the following string:
```
sale_.name =Q E
```

Comment (edeesis) [reply data-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java:1034]: Ah, found the correct one. It's Matcher.quoteReplacement

File: data-processor/src/test/groovy/io/micronaut/data/model/query/builder/SqlQueryBuilderSpec.groovy [hunk 4]
```diff
@@ -102,6 +102,52 @@ interface MyRepository {
         builder.buildInsert(annotationMetadata, entity).query == 'INSERT INTO sale (name,data,quantities,extra_data,data_list) VALUES ($1,to_json($2::json),to_json($3::json),to_json($4::json),to_json($5::json))'
     }
 
+    @Requires({ javaVersion >= 1.8 })
```
Comment (edeesis) [inline data-processor/src/test/groovy/io/micronaut/data/model/query/builder/SqlQueryBuilderSpec.groovy:105]: this test still fails, working on fixing it.

**Comment by edeesis** [comment]
@dstepanov Thanks for the review! Barring any test failures, should be good now.

File: data-processor/src/test/groovy/io/micronaut/data/model/query/builder/SqlQueryBuilderSpec.groovy (hunk 4 above)
Comment (edeesis) [inline data-processor/src/test/groovy/io/micronaut/data/model/query/builder/SqlQueryBuilderSpec.groovy:105]: I wasn't sure why the test above was `@Required({ javaVersion <= 1.8 })`, but my local computer is Java 17, so I made this >= 1.8. If you want me to switch it back to 1.8, just let me know. Or if you want me to remove the Requires, I can do that too.

**Comment by edeesis** [comment]
@dstepanov let me know if you need me to do anything else here!

**Comment by dstepanov** [comment]
Thanks for the contribution!
