### PR TITLE
Use ByteArrayCodec for byte array

### LINKED ISSUE #3165: [MongoDB] ByteArray is stored as an Array instead of Binary since 4.9.4
### Expected Behavior

ByteArray to be stored as Binary data type in Mongo

### Actual Behaviour

Since the 4.9.4 update ByteArray is stored as an array of Ints, which increases the used storage size a lot:

image

It could be related to this change: https://github.com/micronaut-projects/micronaut-data/commit/ae81d87fba97c2aa71900da2c1e075f9e484bdc4#diff-57d1783e0cc7b290c77c65415c2f14d4f800bd3b108a3489b4879bd1864c811c

If this is intended as a feature, please suggest a way to get the old behavior back(store a Binary) when using the latest version.

### Steps To Reproduce

1. Create a Mongo Object in 4.9.4
2. Store the object in Mongo
3. Switch to 4.9.3
4. Store the same object in Mongo

### Environment Information

- Operating System: Windows
- JDK Version: Oracle OpenJDK 21.0.2

### Example Application

_No response_

### Version

4.6.3

### PR DESCRIPTION
**Pull request by radovanradic**
Should fix issue #3165 when saving/reading byte[] in Mongo

### CODE REVIEW

**Comment by radovanradic** [comment]
Sonar has gone crazy, it reports issues unrelated to this PR changes.

**Review by graemerocher — APPROVED** [review]

File: data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java [hunk 1]
```diff
@@ -181,11 +182,17 @@ public <T> Deserializer<? extends T> findDeserializer(Argument<? extends T> type
             return mappedCodec.deserializer;
         }
         if (codec != null) {
-            // Eliminate codecs for basic types and collections
-            Class<? extends T> encoderClass = codec.getEncoderClass();
-            if (!ClassUtils.isJavaLangType(encoderClass)
-                && !Map.class.isAssignableFrom(encoderClass)
-                && !Iterable.class.isAssignableFrom(encoderClass)) {
+            // Eliminate codecs for basic types (except byte array) and collections
+            boolean useCodec;
```
Comment (dstepanov) [inline data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java]: Can you please extract the check into some util class?

**Review by dstepanov — CHANGES_REQUESTED** [review]

File: data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java (hunk 1 above)
Comment (radovanradic) [reply data-mongodb/src/main/java/io/micronaut/data/mongodb/serde/DataDecoderContext.java]: Makes sense, done in b46944aaf433ca513592de8607c709b6a77ccab9

**Review by dstepanov — APPROVED** [review]
