### PR TITLE
Fix Custom INSERT statement with Multitenancy nulls out the tenantId

### LINKED ISSUE #3549: Kotlin/KSP 2 - Custom INSERT statement with Multitenancy nulls out the tenantId
### Expected Behavior

I should be able to use the custom `@Query()` annotation with an INSERT INTO in a Micronaut Data application that uses Multi-tenancy. This only happens when inserting a collection.
This only happens when using KSP2!

```kotlin
@JdbcRepository(dialect = Dialect.H2)
@io.micronaut.transaction.annotation.Transactional
interface PersonRepository : CrudRepository<Person, Int> {

    // DOES NOT WORK
    @Query(
        value = """
            INSERT INTO persons(id, firstName, lastName, tenantId)
            VALUES(:id, :firstName, :lastName, :tenantId)
        """,
        readOnly = false
    )
    fun insertWithQuery(persons: Iterable<Person>): Int

    // WORKS GREAT
    @Query(
        value = """
            INSERT INTO persons(id, firstName, lastName, tenantId)
            VALUES(:id, :firstName, :lastName, :tenantId)
        """,
        readOnly = false
    )
    fun insertWithQueryTheLongWay(id: Int, firstName: String, lastName: String, tenantId: String): Int
}
```

### Actual Behaviour

The `tenantId` field of the inserted object is nulled out.

```
   14:09:20.627 [pool-1-thread-1 @coroutine#5] DEBUG io.micronaut.data.query - Executing SQL query:
                INSERT INTO persons(id, firstName, lastName, tenantId)
                VALUES(?, ?, ?, ?)

    14:09:20.628 [pool-1-thread-1 @coroutine#5] TRACE io.micronaut.data.query - Binding parameter at position 1 to value 1 with data type: INTEGER
    14:09:20.628 [pool-1-thread-1 @coroutine#5] TRACE io.micronaut.data.query - Binding parameter at position 2 to value First with data type: STRING
    14:09:20.628 [pool-1-thread-1 @coroutine#5] TRACE io.micronaut.data.query - Binding parameter at position 3 to value Last with data type: STRING
    14:09:20.628 [pool-1-thread-1 @coroutine#5] TRACE io.micronaut.data.query - Binding parameter at position 4 to value null with data type: STRING
    14:09:20.628 [pool-1-thread-1 @coroutine#5] TRACE io.micronaut.data.query - Binding parameter at position 1 to value 2 with data type: INTEGER
    14:09:20.628 [pool-1-thread-1 @coroutine#5] TRACE io.micronaut.data.query - Binding parameter at position 2 to value Second with data type: STRING
    14:09:20.628 [pool-1-thread-1 @coroutine#5] TRACE io.micronaut.data.query - Binding parameter at position 3 to value Last with data type: STRING
    14:09:20.628 [pool-1-thread-1 @coroutine#5] TRACE io.micronaut.data.query - Binding parameter at position 4 to value null with data type: STRING
```

This is the log output for the "Long Way" query:
```
    14:09:20.656 [pool-1-thread-1 @coroutine#6] DEBUG io.micronaut.data.query - Executing Query:
                INSERT INTO persons(id, firstName, lastName, tenantId)
                VALUES(?, ?, ?, ?)

    14:09:20.656 [pool-1-thread-1 @coroutine#6] TRACE io.micronaut.data.query - Binding parameter at position 1 to value 1 with data type: INTEGER
    14:09:20.656 [pool-1-thread-1 @coroutine#6] TRACE io.micronaut.data.query - Binding parameter at position 2 to value First with data type: STRING
    14:09:20.656 [pool-1-thread-1 @coroutine#6] TRACE io.micronaut.data.query - Binding parameter at position 3 to value Last with data type: STRING
    14:09:20.656 [pool-1-thread-1 @coroutine#6] TRACE io.micronaut.data.query - Binding parameter at position 4 to value THE_TENANT with data type: STRING
    14:09:20.656 [pool-1-thread-1 @coroutine#6] TRACE io.micronaut.data.query - Update operation updated 1 records
    14:09:20.657 [pool-1-thread-1 @coroutine#6] DEBUG io.micronaut.data.query - Executing Query:
                INSERT INTO persons(id, firstName, lastName, tenantId)
                VALUES(?, ?, ?, ?)

    14:09:20.657 [pool-1-thread-1 @coroutine#6] TRACE io.micronaut.data.query - Binding parameter at position 1 to value 2 with data type: INTEGER
    14:09:20.657 [pool-1-thread-1 @coroutine#6] TRACE io.micronaut.data.query - Binding parameter at position 2 to value Second with data type: STRING
    14:09:20.657 [pool-1-thread-1 @coroutine#6] TRACE io.micronaut.data.query - Binding parameter at position 3 to value Last with data type: STRING
    14:09:20.657 [pool-1-thread-1 @coroutine#6] TRACE io.micronaut.data.query - Binding parameter at position 4 to value THE_TENANT with data type: STRING
    14:09:20.657 [pool-1-thread-1 @coroutine#6] TRACE io.micronaut.data.query - Update operation updated 1 records
```

### Steps To Reproduce

Check out my repo: https://github.com/charlie-harvey-beable/micronaut-ksp-data-multitenant

```
./gradlew build --info
```

### Environment Information

Mac. JDK 21

### Example Application

https://github.com/charlie-harvey-beable/micronaut-ksp-data-multitenant

### Version

4.9.4

### PR DESCRIPTION
**Pull request by radovanradic**
Fix for issue #3549

### CODE REVIEW

File: data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/BaseOperations.java [hunk 1]
```diff
@@ -73,6 +73,7 @@ protected void checkOptimisticLocking(long expected, long received) {
      */
     public void persist() {
         try {
+            collectAutoPopulatedPreviousValues();
```
Comment (radovanradic) [inline data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/BaseOperations.java:76]: Query parameter for tenantId in example given in the issue report are marked as requiresPreviousPopulatedValue and auto populate was not working for insert and I guess it is needed for this case.

**Comment by radovanradic** [comment]
Something changed recently causing build to fail for this test intemittently
```
[:micronaut-data-r2dbc:test](https://ge.micronaut.io/s/35nhjeynz3g4c/tests/task/:micronaut-data-r2dbc:test)
[io.micronaut.data.r2dbc.oraclexe.OracleXEMultitenancySpec](https://ge.micronaut.io/s/35nhjeynz3g4c/tests/task/:micronaut-data-r2dbc:test/details/io.micronaut.data.r2dbc.oraclexe.OracleXEMultitenancySpec)
47 results in the previous 7 days, 32 passed, 9 failed, 6 flaky[View test history](https://ge.micronaut.io/scans/tests?search.startTimeMax=1760392799999&search.startTimeMin=1759701600000&tests.container=io.micronaut.data.r2dbc.oraclexe.OracleXEMultitenancySpec&tests.test=test%20datasource%20multitenancy)
Failed
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.data.r2dbc.config.R2dbcSchemaGenerator] could not be loaded: Error instantiating bean of type  [io.r2dbc.spi.ConnectionFactoryOptions$Builder]

Message: Test resources service wasn't able to revolve expression 'r2dbc.datasources.foo.url': java.net.http.HttpTimeoutException: request timed out
Path Taken:
new @i.m.c.a.Context i.m.d.r.c.R2dbcSchemaGenerator(List<DataR2dbcConfiguration> configurations, R2dbcSchemaHandler sch
```

**Comment by charlie-harvey-beable** [comment]
Wow! I can't believe you took my issue so quickly and were able to make these changes and tests so fast. Amazing! Thank you so much.

**Review by dstepanov — APPROVED** [review]
