### PR TITLE
Don't create join table when there is join column configured on foreign key

### LINKED ISSUE #2385: Micronaut Data does not support @JoinColumn correctly
### Expected Behavior

Given (Unidirectional one to many, no join table):
See also https://docs.jboss.org/hibernate/annotations/3.5/reference/en/html_single/#entity-mapping-association
```
@Introspected
@Table(schema = "my_schema")
@MappedEntity("e")
public class E {
  @Id
  @GeneratedValue
  Long id;
  long catId;
  long eId;
  String name;
  @OneToMany
  @JoinColumn(name = "e_id", referencedColumnName = "e_id")
  @JoinColumn(name = "cat_id", referencedColumnName = "cat_id")
  List<F> f;
  ...
}

@Introspected
@Table(schema = "my_schema")
@MappedEntity("f")
public class F {
  @Id
  @GeneratedValue
  Long id;
  long eId;
  long catId;
  String name;
  ...
}

@JdbcRepository(dialect = Dialect.POSTGRES)
public abstract class ETable implements CrudRepository<E, Long> {

  @Join(value = "f", alias = "f_", type = Join.Type.LEFT_FETCH)
  @Where("@.cat_id = :catId")
  public abstract List<E> findByCatId(long catId);
}
```

I'd expect something like the following query to be generated:
```
SELECT
  e.id, e.cat_id, e.name, e.e_id,
  f.id, f.e_id, f.cat_id, f.name
FROM my_schema.e e
LEFT JOIN my_schema.f ON e.cat_id=f.cat_id AND e.e_id=f.e_id
WHERE e.cat_id=?
```

### Actual Behaviour

This is what was generated:
```
SELECT e_."id",e_."cat_id",e_."name",e_."e_id",f_."id" AS f_id,f_."e_id" AS f_e_id,f_."cat_id" AS f_cat_id,f_."name" AS f_name
FROM "my_schema"."e" e_
LEFT JOIN "e_f" f_e_f_ ON e_."id"=f_e_f_."e_id" 
LEFT JOIN "my_schema"."f" f_ ON f_e_f_."f_id"=f_."id"
WHERE (e_."cat_id" = ? AND (e_.cat_id =?))
```

Notice that:
1. The column names were completely ignored
2. A join table has sprang out from nowhere. Note @JoinTable was not used.

### Steps To Reproduce

See sample code

### Environment Information

Linux / JDK 17 / Micronaut Data 3.9.6

### Example Application

https://github.com/RonBarkan/doublejoinbug/blob/master/src/test/java/com/example/JoinTest.java

### Version

Micronaut Data 3.9.6

### PR DESCRIPTION
**Pull request by radovanradic**
This should fix #2385 , at least I think this is similar to how Hibernate treats JoinColumn annotation.
Hopefully it will not cause some regression, the tests are looking ok with this change.

### CODE REVIEW

File: data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder.java [hunk 1]
```diff
@@ -300,9 +302,17 @@ String buildJoinTableInsert(@NonNull PersistentEntity entity, @NonNull Associati
...
-        return association.isForeignKey() &&
-                !association.getAnnotationMetadata()
-                        .stringValue(Relation.class, "mappedBy").isPresent();
+        if (!association.isForeignKey()) {
+            return false;
+        }
+        if (association.getAnnotationMetadata().stringValue(Relation.class, "mappedBy").isPresent()) {
+            return false;
+        }
+        AnnotationValue<JoinColumns> joinColumnsAnnotationValue  = association.getAnnotationMetadata().getAnnotation(JoinColumns.class);
```
Comment (radovanradic) [inline data-model/src/main/java/io/micronaut/data/model/query/builder/sql/SqlQueryBuilder.java:311]: This means association is foreign key, has no mappedBy and no join column and join table is needed for foreign key.

File: data-processor/src/test/groovy/io/micronaut/data/processor/visitors/RelationshipSpec.groovy [hunk 2]
```diff
@@ -354,7 +354,7 @@ class User {
...
                     'SELECT user_."id",user_authorities_."id" AS authorities_id,user_authorities_."name" AS authorities_name,user_authorities_."user_id" AS authorities_user_id FROM "user" user_ INNER JOIN "authority" user_authorities_ ON user_."u_id"=user_authorities_."a_id" AND user_."y_id"=user_authorities_."x_id" WHERE (user_."id" = ?)',
-                    'SELECT user_."id",user_authorities_."id" AS authorities_id,user_authorities_."name" AS authorities_name,user_authorities_."user_id" AS authorities_user_id FROM "user" user_ INNER JOIN "user_authority" user_authorities_user_authority_ ON user_."id"=user_authorities_user_authority_."user_id"  INNER JOIN "authority" user_authorities_ ON user_authorities_user_authority_."authority_id"=user_authorities_."id" WHERE (user_."id" = ?)',
+                    'SELECT user_."id",user_authorities_."id" AS authorities_id,user_authorities_."name" AS authorities_name,user_authorities_."user_id" AS authorities_user_id FROM "user" user_ INNER JOIN "authority" user_authorities_ ON user_."a_id"=user_authorities_."u_id" AND user_."x_id"=user_authorities_."y_id" WHERE (user_."id" = ?)',
```
Comment (radovanradic) [inline data-processor/src/test/groovy/io/micronaut/data/processor/visitors/RelationshipSpec.groovy:357]: No JoinTable since there is JoinColumn earlier configured on FK

**Review by dstepanov — APPROVED** [review]
