### PR TITLE
issues/3045: HQL where in with empty entity list throws NPE

### LINKED ISSUE #3045: HQL `where in :entityList` when entityList is empty, fails with NPE
### Expected Behavior

The HQL `select entityA a where a.entityB in :listOfEntityBs` with an empty list does not throw an NPE.

### Actual Behaviour

Since 4.1, it seems that if an emptyList is passed into the repository function, it will throw an NPE down in the Hibernate code when Hibernate tries to derive the argument type by using `value.getClass()`

### Steps To Reproduce

1. Pull my branch (issue-3045) at https://github.com/rawilder/micronaut-data/tree/issue-3045
2. Run the test: AbstractHibernateQuerySpec::"test where in empty list of entities"
3. Observe NPE

### Environment Information

- MacOS
- jdk 17 corretto
- micronaut data 4.8.x

### Example Application

https://github.com/rawilder/micronaut-data/blob/issue-3045/data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/AbstractHibernateQuerySpec.groovy#L74

### Version

4.8.x

### PR DESCRIPTION
**Pull request by rawilder**
Important to note I couldn't run some of the test suites successfully on my M1, but those that did run passed locally.

* add test for the issue
* in HibernateJpaOperations, call setParameterList instead of setParameter where appropriate
* in AbstractHibernateOperations, evaluate any bindings that have an index, rather than just isNativeQuery bindings
* [use value in setParameterList instead of using parameterIndex as the value](https://github.com/micronaut-projects/micronaut-data/pull/3046/files#diff-8a07d811dde5fec39c77f6caa58650686ad9157064c10551c16ccd63041d4244L189)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

### CODE REVIEW

File: data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java [hunk 1]
```diff
@@ -470,7 +470,7 @@ public Object convert(Class<?> converterClass, Object value, Argument<?> argumen
             @Override
             public void bindOne(QueryParameterBinding binding, Object value) {
                 String parameterName = Objects.requireNonNull(binding.getName(), "Parameter name cannot be null!");
-                if (storedQuery.isNative()) {
+                if (binding.getParameterIndex() != -1) {
```
Comment (rawilder) [inline data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java:473]: This is an attempt to attack a more abstract problem than maybe this issue poses, I thought this code path could be good for more than the native query context (as this issue shows)

File: data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java [hunk 2]
```diff
@@ -177,14 +180,14 @@ protected void setParameter(CommonQueryContract query, int parameterIndex, Objec
...
+            value = Collections.emptyList();
+        }
+        query.setParameterList(parameterIndex, value);
     }
 
     @Override
     protected void setParameterList(CommonQueryContract query, int parameterIndex, Collection<Object> value, Argument<?> argument) {
-        if (value == null) {
-            value = Collections.emptyList();
-        }
```
Comment (rawilder) [inline data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java]: `value` is unused, also I am not quite sure what this function is doing with `query.setParameter(parameterIndex, parameterIndex);`

File: data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java [hunk 3]
```diff
@@ -152,8 +152,11 @@ protected void setParameter(CommonQueryContract query, String parameterName, Obj
 
     @Override
     protected void setParameterList(CommonQueryContract query, String parameterName, Collection<Object> value) {
+        if (value == null) {
```
Comment (rawilder) [inline data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java:155]: added these null checks to a few more places where a collection was guaranteed and `value` was used

File: data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java (hunk 2 above)
Comment (radovanradic) [reply data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java]: That's a bug. Please change that line to `query.setParameterList(parameterIndex, value);`.

File: data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/AbstractHibernateQuerySpec.groovy [hunk 4]
```diff
@@ -71,6 +71,14 @@ abstract class AbstractHibernateQuerySpec extends AbstractQuerySpec {
     @Inject
     RelPersonRepository relPersonRepo
 
+    void "test where in empty list of entities"() {
+        when:
+            def found = ratingRepository.findByAuthors(List.of())
```
Comment (radovanradic) [inline data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/AbstractHibernateQuerySpec.groovy]: The test is failing because `ratingRepository` does not have `findByAuthors(List)` method.
You can add this method `public abstract List<Book> findByAuthorInList(List<Author> authors);` to the `BookRepository` and then update test and maybe add case to find in non empty list
```
void "test where in empty list of entities"() {
        when:
        def found = bookRepository.findByAuthorInList(List.of())
        then:
        found.empty
        when:
        def author = authorRepository.findByName("Stephen King")
        found = bookRepository.findByAuthorInList(List.of(author))
        then:
        !found.empty
    }
```

File: data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java (hunk 1 above)
Comment (radovanradic) [reply data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java:473]: This seems to fix the issue, which I believe is caused in https://github.com/micronaut-projects/micronaut-data/blob/4.8.x/data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/query/DefaultBindableParametersStoredQuery.java#L202-L207
```
List<Object> values = binding.isExpandable() ? expandValue(value, binding.getDataType()) : null;
        if (values != null && values.isEmpty()) {
            // Empty collections / array should always set at least one value
            value = null;
            values = null;
        }
```
as Micronaut binder didn't expect empty list for IN clause.
@dstepanov not sure if this change could cause some other issues.

File: data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/AbstractHibernateQuerySpec.groovy (hunk 4 above)
Comment (rawilder) [reply data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/AbstractHibernateQuerySpec.groovy]: Oh goodness that's embarrassing, I promise it did fail when I did define that function 😅 I tried to make two separate branches, one with the test and one with the test and fix and I think I lost the repository changes in that shuffle

Comment (radovanradic) [reply data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/AbstractHibernateQuerySpec.groovy]: I know, it happens when need to fork and create PR from new branch there.

File: data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java (hunk 1 above)
Comment (rawilder) [reply data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java:473]: The emptyList for IN with non-entity types works (at least [basic types](https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2#a486)), maybe by accident, maybe intentionally doesn't support null, I'm unsure. Hibernate [EntityJavaType::isInstance](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/EntityJavaType.java#L56) doesn't protect against null, but it's parent [JavaType](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JavaType.java#L106) doesn't have the same issue (which this used for basic types)

File: data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/AbstractHibernateQuerySpec.groovy (hunk 4 above)
Comment (rawilder) [reply data-hibernate-jpa/src/test/groovy/io/micronaut/data/hibernate/AbstractHibernateQuerySpec.groovy]: Updated to use BookRepository instead to utilize existing seed data

File: data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java [hunk 5]
```diff
@@ -152,8 +152,11 @@ protected void setParameter(CommonQueryContract query, String parameterName, Obj
...
+            value = Collections.emptyList();
+        }
         // Passing collection as param like this as well, before Hibernate 6 there was other method to pass collection
-        query.setParameter(parameterName, value);
+        query.setParameterList(parameterName, value);
```
Comment (rawilder) [inline data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/HibernateJpaOperations.java:159]: Important to point out, setParameterList here instead of setParameter

File: data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java (hunk 1 above)
Comment (dstepanov) [inline data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java:473]: @rawilder Does it work without the native check change?

Comment (radovanradic) [reply data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java:473]: Then it goes into else branch 
```
else if (bindNamed) {
                    setParameter(q, parameterName, value);
                } else {
                    setParameter(q, index, value);
                }
```
and since it was an empty collection, in binding method I posted above it is being set to null. And in this else branch, we don't have pointer to the argument type, don't know if this is collection or not since it is null and we set null parameter to Hibernate and then it fails here
```
@Override
	public boolean isInstance(Object value) {
		final LazyInitializer lazyInitializer = extractLazyInitializer( value );
		final Class<T> javaTypeClass = getJavaTypeClass();
		if ( lazyInitializer != null ) {
			return javaTypeClass.isAssignableFrom( lazyInitializer.getPersistentClass() )
					|| javaTypeClass.isAssignableFrom( lazyInitializer.getImplementationClass() );
		}
		else {
			return javaTypeClass.isAssignableFrom( value.getClass() );
		}
	}
```
on line `return javaTypeClass.isAssignableFrom( value.getClass() );` because `value` is null throws NPE.
For difference, code in `if` branch tries to convert null parameter to an empty collection if recognizes it is collection argument.

Comment (radovanradic) [reply data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java:473]: From what I can see by debugging code with this change, this branch
```
else if (bindNamed) {
                    setParameter(q, parameterName, value);
                }
```
is used only in save, update, delete methods.

Comment (rawilder) [reply data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java:473]: Any thoughts on the above @dstepanov ?

Comment (dstepanov) [reply data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java:473]: Can you please target 4.9

Comment (rawilder) [reply data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java:473]: Retargeted. I changed this line back to `isNative` and reran the tests for good measure and the one I added failed, so I changed it back to the `getParameterIndex` condition.

Comment (rawilder) [reply data-hibernate-jpa/src/main/java/io/micronaut/data/hibernate/operations/AbstractHibernateOperations.java:473]: Okay monkeyed with the branch to get it to be just the work's commits again, branched off of 4.9.x, should be the same changes (minus the accidentally included imports)
